from Gym.parameter_controllers.ab_program_simulation import ABProgramSimulation_ParameterController
from Gym.parameter_controllers.add_multiple_divisible_counting import AddMultiple_Divisible_Counting_ParameterController
from Gym.parameter_controllers.addition_table import AdditionTable_ParameterController
from Gym.parameter_controllers.almost_complete_graph_cycle_counting import AlmostCompleteGraphCycleCounting_ParameterController
from Gym.parameter_controllers.and_or_sequence_counting import AndOr_Sequence_Counting_ParameterController
from Gym.parameter_controllers.anti_palindromic_substring_counting import AntiPalindromicSubstringCounting_ParameterController
from Gym.parameter_controllers.axis_k_center import Axis_KCenter_ParameterController
from Gym.parameter_controllers.baj_bytecomputer import BAJBytecomputer_ParameterController
from Gym.parameter_controllers.banned_point_superset_path_counting import BannedPointSupersetPathCounting_ParameterController
from Gym.parameter_controllers.banyan_heart import BanyanHeart_ParameterController
from Gym.parameter_controllers.bez_minimalist_security import BEZMinimalistSecurity_ParameterController
from Gym.parameter_controllers.bezout_identity import BezoutIdentity_ParameterController
from Gym.parameter_controllers.binario import Binario_ParameterController
from Gym.parameter_controllers.binario_no_adjacency_requirement import Binario_NoAdjacencyRequirement_ParameterController
from Gym.parameter_controllers.binary_alternation import BinaryAlternation_ParameterController
from Gym.parameter_controllers.binary_string_no_adjacent_count import BinaryStringNoAdjacentCount_ParameterController
from Gym.parameter_controllers.binary_linear_equation_solution_counting import BinaryLinearEquation_SolutionCounting_ParameterController
from Gym.parameter_controllers.binary_tree_leaf_num_expectation import BinaryTreeLeafNumExpectation_ParameterController
from Gym.parameter_controllers.bit_equation_counting import BitEquationCounting_ParameterController
from Gym.parameter_controllers.bitand_zero_path_counting import BitAndZero_PathCounting_ParameterController
from Gym.parameter_controllers.bitwise_operation_sequence_counting import BitwiseOperationSequenceCounting_ParameterController
from Gym.parameter_controllers.block_image import BlockImage_ParameterController
from Gym.parameter_controllers.bounded_adjacency_difference_permutation_counting import BoundedAdjacencyDifference_Permutation_Counting_ParameterController
from Gym.parameter_controllers.bounded_interval_intersection import BoundedIntervalIntersection_ParameterController
from Gym.parameter_controllers.bounded_mean_subarray_counting import BoundedMeanSubarrayCounting_ParameterController
from Gym.parameter_controllers.bounded_subarray_counting import BoundedSubarrayCounting_ParameterController
from Gym.parameter_controllers.box_scheduling import BoxScheduling_ParameterController
from Gym.parameter_controllers.bridge import Bridge_ParameterController
from Gym.parameter_controllers.bubble_swap_lower_bound_permutation_counting import BubbleSwapLowerBound_PermutationCounting_ParameterController
from Gym.parameter_controllers.bucket_sorting import BucketSorting_ParameterController
from Gym.parameter_controllers.campfire_party import CampfireParty_ParameterController
from Gym.parameter_controllers.campsite_puzzle import CampsitePuzzle_ParameterController
from Gym.parameter_controllers.canon import Canon_ParameterController
from Gym.parameter_controllers.cantor_expansion import CantorExpansion_ParameterController
from Gym.parameter_controllers.capital_city_effect import CapitalCityEffect_ParameterController
from Gym.parameter_controllers.card_coloring_counting import CardColoringCounting_ParameterController
from Gym.parameter_controllers.catalan_number_mod import CatalanNumberMod_ParameterController
from Gym.parameter_controllers.check_all_cycle_xor_zero import CheckAllCycleXorZero_ParameterController
from Gym.parameter_controllers.cho_hamsters import ChoHamsters_ParameterController
from Gym.parameter_controllers.cinema import Cinema_ParameterController
from Gym.parameter_controllers.circuit import Circuit_ParameterController
from Gym.parameter_controllers.circulating_decimal_counting import CirculatingDecimalCounting_ParameterController
from Gym.parameter_controllers.circulating_grid import CirculatingGrid_ParameterController
from Gym.parameter_controllers.cleaning_up import CleaningUp_ParameterController
from Gym.parameter_controllers.clear_symmetry import ClearSymmetry_ParameterController
from Gym.parameter_controllers.clique_independent_set_partitioning_counting import Clique_IndependentSet_Partitioning_Counting_ParameterController
from Gym.parameter_controllers.coin_square_game import CoinSquareGame_ParameterController
from Gym.parameter_controllers.coloring_counting import ColoringCounting_ParameterController
from Gym.parameter_controllers.combination_odd_subsequence_counting import CombinationOddSubsequenceCounting_ParameterController
from Gym.parameter_controllers.concatenation_partition_counting_sum import ConcatenationPartitionCountingSum_ParameterController
from Gym.parameter_controllers.congruent_equation import CongruentEquation_ParameterController
from Gym.parameter_controllers.construct_hack_interval import ConstructHackInterval_ParameterController
from Gym.parameter_controllers.convex_hull import ConvexHull_ParameterController
from Gym.parameter_controllers.cornfield import Cornfield_ParameterController
from Gym.parameter_controllers.countdown import Countdown_ParameterController
from Gym.parameter_controllers.cow_dance_show import CowDanceShow_ParameterController
from Gym.parameter_controllers.crt import CRT_ParameterController
from Gym.parameter_controllers.cryptarithmetic import Cryptarithmetic_ParameterController
from Gym.parameter_controllers.cube_fixed_local_maximum_counting import Cube_FixedLocalMaximumCounting_ParameterController
from Gym.parameter_controllers.cycle_counting import CycleCounting_ParameterController
from Gym.parameter_controllers.decreasing_digit_counting import DecreasingDigitCounting_ParameterController
from Gym.parameter_controllers.degree_fixed_spanning_tree import DegreeFixed_SpanningTree_ParameterController
from Gym.parameter_controllers.delta_min_popcount import DeltaMinPopcount_ParameterController
from Gym.parameter_controllers.delta_nim_game import DeltaNimGame_ParameterController
from Gym.parameter_controllers.derangement_extension import DerangementExtension_ParameterController
from Gym.parameter_controllers.difference_constraint_system import DifferenceConstraintSystem_ParameterController
from Gym.parameter_controllers.difference_constraint_system_dag import DifferenceConstraintSystemDAG_ParameterController
from Gym.parameter_controllers.different_color_pairing import DifferentColorPairing_ParameterController
from Gym.parameter_controllers.differentiate import Differentiate_ParameterController
from Gym.parameter_controllers.digit_lis_counting import DigitLISCounting_ParameterController
from Gym.parameter_controllers.digit_sum_interval import DigitSumInterval_ParameterController
from Gym.parameter_controllers.discrete_logarithm import DiscreteLogarithm_ParameterController
from Gym.parameter_controllers.disinfection import Disinfection_ParameterController
from Gym.parameter_controllers.distinct_array_permutation import DistinctArrayPermutation_ParameterController
from Gym.parameter_controllers.distinct_edge_colored_complete_graph_counting import DistinctEdgeColoredCompleteGraphCounting_ParameterController
from Gym.parameter_controllers.division import Division_ParameterController
from Gym.parameter_controllers.divisor_flip_expectation import DivisorFlipExpectation_ParameterController
from Gym.parameter_controllers.double_cross_counting import DoubleCrossCounting_ParameterController
from Gym.parameter_controllers.double_palindromic_string_counting import DoublePalindromicStringCounting_ParameterController
from Gym.parameter_controllers.double_stack_sorting import DoubleStackSorting_ParameterController
from Gym.parameter_controllers.dyn_dynamite import DynDynamite_ParameterController
from Gym.parameter_controllers.eight_digit_puzzle import EightDigitPuzzle_ParameterController
from Gym.parameter_controllers.emperor_worries import EmperorWorries_ParameterController
from Gym.parameter_controllers.energy_storage_meter import EnergyStorageMeter_ParameterController
from Gym.parameter_controllers.euclid_game import EuclidGame_ParameterController
from Gym.parameter_controllers.even_degree_graph_partitioning import EvenDegreeGraphPartitioning_ParameterController
from Gym.parameter_controllers.expression_adding_parenthese_counting import Expression_AddingParenthese_Counting_ParameterController
from Gym.parameter_controllers.face_right_way import FaceRightWay_ParameterController
from Gym.parameter_controllers.factorial_trailing_zero_count import FactorialTrailingZeroCount_ParameterController
from Gym.parameter_controllers.fbi_binary_tree import FBI_BinaryTree_ParameterController
from Gym.parameter_controllers.fibonacci import Fibonacci_ParameterController
from Gym.parameter_controllers.fibonacci_containing_counting import FibonacciContainingCounting_ParameterController
from Gym.parameter_controllers.fibtrain import Fibtrain_ParameterController
from Gym.parameter_controllers.firework_show import FireworkShow_ParameterController
from Gym.parameter_controllers.fixed_mod_k_selection_counting import FixedModK_Selection_Counting_ParameterController
from Gym.parameter_controllers.fixed_one_edge_num_spanning_tree import FixedOneEdgeNum_SpanningTree_ParameterController
from Gym.parameter_controllers.fractional_programming import FractionalProgramming_ParameterController
from Gym.parameter_controllers.fractional_programming_bipartite_graph_matching import FractionalProgramming_BipartiteGraphMatching_ParameterController
from Gym.parameter_controllers.futoshiki_puzzle import FutoshikiPuzzle_ParameterController
from Gym.parameter_controllers.gas_fire_extinguishers import GasFireExtinguishers_ParameterController
from Gym.parameter_controllers.gaussian_elimination import GaussianElimination_ParameterController
from Gym.parameter_controllers.gcd_fibonacci_product import GCDFibonacciProduct_ParameterController
from Gym.parameter_controllers.gcd_lcm_counting import GcdLcmCounting_ParameterController
from Gym.parameter_controllers.gcd_one_counting import GCDOne_Counting_ParameterController
from Gym.parameter_controllers.gcd_prime_counting import GCDPrime_Counting_ParameterController
from Gym.parameter_controllers.gold_washing import GoldWashing_ParameterController
from Gym.parameter_controllers.gra_minima_game import GraMinimaGame_ParameterController
from Gym.parameter_controllers.grade_ranking_counting import GradeRankingCounting_ParameterController
from Gym.parameter_controllers.graph_contain_tree_counting import GraphContainTreeCounting_ParameterController
from Gym.parameter_controllers.graph_isomorphism import GraphIsomorphism_ParameterController
from Gym.parameter_controllers.grid_bfs import GridBFS_ParameterController
from Gym.parameter_controllers.grid_coloring_counting import GridColoringCounting_ParameterController
from Gym.parameter_controllers.grid_component import GridComponent_ParameterController
from Gym.parameter_controllers.grid_local_minimum_counting import GridLocalMinimumCounting_ParameterController
from Gym.parameter_controllers.grid_path_counting_with_blocks import GridPathCountingWithBlocks_ParameterController
from Gym.parameter_controllers.grid_parity_construction import GridParityConstruction_ParameterController
from Gym.parameter_controllers.grid_triangle_counting import GridTriangleCounting_ParameterController
from Gym.parameter_controllers.halving_chain_counting import HalvingChainCounting_ParameterController
from Gym.parameter_controllers.hamiltonian_path import HamiltonianPath_ParameterController
from Gym.parameter_controllers.hamiltonian_path_existence import HamiltonianPathExistence_ParameterController
from Gym.parameter_controllers.heap_counting import HeapCounting_ParameterController
from Gym.parameter_controllers.hitori_puzzle import HitoriPuzzle_ParameterController
from Gym.parameter_controllers.hungry_rabbit import HungryRabbit_ParameterController
from Gym.parameter_controllers.hur_warehouse_store import HURWarehouseStore_ParameterController
from Gym.parameter_controllers.imp_party import ImpParty_ParameterController
from Gym.parameter_controllers.individual_sum_bounded_sequence_counting import IndividualSumBounded_SequenceCounting_ParameterController
from Gym.parameter_controllers.integer_factorization_counting import IntegerFactorizationCounting_ParameterController
from Gym.parameter_controllers.integer_programming import IntegerProgramming_ParameterController
from Gym.parameter_controllers.integral import Integral_ParameterController
from Gym.parameter_controllers.inversion_pair import InversionPair_ParameterController
from Gym.parameter_controllers.inversion_pair_k_counting import InversionPairK_Counting_ParameterController
from Gym.parameter_controllers.josephus import Josephus_ParameterController
from Gym.parameter_controllers.jug_puzzle import JugPuzzle_ParameterController
from Gym.parameter_controllers.k_partition import KPartition_ParameterController
from Gym.parameter_controllers.kakurasu import Kakurasu_ParameterController
from Gym.parameter_controllers.kidding_me import KiddingMe_ParameterController
from Gym.parameter_controllers.king_sorting import KingSorting_ParameterController
from Gym.parameter_controllers.klo_blocks import KloBlocks_ParameterController
from Gym.parameter_controllers.knapsack import Knapsack_ParameterController
from Gym.parameter_controllers.knights_and_knaves import KnightsAndKnaves_ParameterController
from Gym.parameter_controllers.kos_dicing import KosDicing_ParameterController
from Gym.parameter_controllers.kth_binary_tree import Kth_BinaryTree_ParameterController
from Gym.parameter_controllers.kth_semi_balanced_bracket_sequence import Kth_SemiBalancedBracketSequence_ParameterController
from Gym.parameter_controllers.kth_subsequence import KthSubsequence_ParameterController
from Gym.parameter_controllers.kur import KUR_ParameterController
from Gym.parameter_controllers.lamp_changing import LampChanging_ParameterController
from Gym.parameter_controllers.land_acquisition import LandAcquisition_ParameterController
from Gym.parameter_controllers.landform_generation_counting import LandformGenerationCounting_ParameterController
from Gym.parameter_controllers.largest_convex_polygon import LargestConvexPolygon_ParameterController
from Gym.parameter_controllers.largest_rectangle_among_points import LargestRectangle_AmongPoints_ParameterController
from Gym.parameter_controllers.las import LAS_ParameterController
from Gym.parameter_controllers.las_laser import LASLaser_ParameterController
from Gym.parameter_controllers.lcm import LCM_ParameterController
from Gym.parameter_controllers.lds_two_counting import LDSTwo_Counting_ParameterController
from Gym.parameter_controllers.light_up_puzzle import LightUpPuzzle_ParameterController
from Gym.parameter_controllers.link_beads import LinkBeads_ParameterController
from Gym.parameter_controllers.lis_lds_concatenation import LIS_LDS_Concatenation_ParameterController
from Gym.parameter_controllers.liz_lollipop import LIZ_Lollipop_ParameterController
from Gym.parameter_controllers.longest_double_palindrome import Longest_DoublePalindrome_ParameterController
from Gym.parameter_controllers.longest_matching_subsequence import Longest_MatchingSubsequence_ParameterController
from Gym.parameter_controllers.longest_maxdiff_bounded_interval.parameter_controller import LongestMaxDiffBoundedInterval_ParameterController
from Gym.parameter_controllers.longest_path import LongestPath_ParameterController
from Gym.parameter_controllers.longest_repeated_palindrome import Longest_RepeatedPalindrome_ParameterController
from Gym.parameter_controllers.maf_mafia import MafMafia_ParameterController
from Gym.parameter_controllers.magic_square_puzzle import MagicSquarePuzzle_ParameterController
from Gym.parameter_controllers.making_grade import MakingGrade_ParameterController
from Gym.parameter_controllers.matrix_binary_exponentiation import Matrix_BinaryExponentiation_ParameterController
from Gym.parameter_controllers.matrix_permutation_both_diagonal_one import MatrixPermutation_BothDiagonalOne_ParameterController
from Gym.parameter_controllers.matrix_permutation_equivalence import MatrixPermutationEquivalence_ParameterController
from Gym.parameter_controllers.matrix_permutation_main_diagonal_one import MatrixPermutation_MainDiagonalOne_ParameterController
from Gym.parameter_controllers.matrix_pooling import MatrixPooling_ParameterController
from Gym.parameter_controllers.matrix_rmq_counting import MatrixRMQCounting_ParameterController
from Gym.parameter_controllers.max_different_group_pair_division import MaxDifferentGroupPairDivision_ParameterController
from Gym.parameter_controllers.max_grid_path_intersection import MaxGridPathIntersection_ParameterController
from Gym.parameter_controllers.max_minimum_after_interval_addition import MaxMinimum_AfterIntervalAddition_ParameterController
from Gym.parameter_controllers.max_mult_split import MaxMultSplit_ParameterController
from Gym.parameter_controllers.max_multiplication_fixed_sum import MaxMultiplicationFixedSum_ParameterController
from Gym.parameter_controllers.max_no_conflicting_bombs import MaxNoConflictingBombs_ParameterController
from Gym.parameter_controllers.max_nonadjacent_k_element_sum import Max_NonAdjacent_KElementSum_ParameterController
from Gym.parameter_controllers.max_permutation import MaxPermutation_ParameterController
from Gym.parameter_controllers.max_rmq_expectation import MaxRMQExpectation_ParameterController
from Gym.parameter_controllers.max_segment_coverage_constraint import MaxSegmentCoverageConstraint_ParameterController
from Gym.parameter_controllers.max_sum_lds import MaxSumLDS_ParameterController
from Gym.parameter_controllers.max_three_square_sum import MaxThreeSquareSum_ParameterController
from Gym.parameter_controllers.max_tree_constrained_permutation_weight import Max_TreeConstrainedPermutation_Weight_ParameterController
from Gym.parameter_controllers.max_tree_k_path_coverage import MaxTree_KPathCoverahe_ParameterController
from Gym.parameter_controllers.max_tree_xor_path import MaxTreeXorPath_ParameterController
from Gym.parameter_controllers.max_weight_palindromic_substring import MaxWeightPalindromicSubstring_ParameterController
from Gym.parameter_controllers.max_xor_path import MaxXorPath_ParameterController
from Gym.parameter_controllers.max_xor_set import MaxXorSet_ParameterController
from Gym.parameter_controllers.maximum_achromatic_number import MaximumAchromaticNumber_ParameterController
from Gym.parameter_controllers.maximum_clique import MaximumClique_ParameterController
from Gym.parameter_controllers.maximum_divisor import MaximumDivisor_ParameterController
from Gym.parameter_controllers.maximum_independent_set_grid import MaximumIndependentSetGrid_ParameterController
from Gym.parameter_controllers.maximum_independent_set_tree import Maximum_IndependentSet_Tree_ParameterController
from Gym.parameter_controllers.maximum_lexicographical_order_subsequence import MaximumLexicographicalOrderSubsequence_ParameterController
from Gym.parameter_controllers.maximum_point_segment_matching import MaximumPointSegmentMatching_ParameterController
from Gym.parameter_controllers.maximum_subsequence_num import Maximum_SubsequenceNum_ParameterController
from Gym.parameter_controllers.maximum_weight_matching import MaximumWeightMatching_ParameterController
from Gym.parameter_controllers.maze import Maze_ParameterController
from Gym.parameter_controllers.min_conversion_to_cycle_cost import MinConversionToCycleCost_ParameterController
from Gym.parameter_controllers.min_cost_reducing_lnds import MinCostReducingLNDS_ParameterController
from Gym.parameter_controllers.min_cost_tree_coverage import MinCostTreeCoverage_ParameterController
from Gym.parameter_controllers.min_cube_assignment import MinCubeAssignment_ParameterController
from Gym.parameter_controllers.min_division_sum_xor import MinDivisionSumXor_ParameterController
from Gym.parameter_controllers.min_inorder_binary_tree import MinInorderBinaryTree_ParameterController
from Gym.parameter_controllers.min_kdivisor_number import MinKDivisorNumber_ParameterController
from Gym.parameter_controllers.min_no_solution_linear_diophantine_equation import MinNoSolutionLinearDiophantineEquation_ParameterController
from Gym.parameter_controllers.min_nonsubstring import MinNonsubstring_ParameterController
from Gym.parameter_controllers.min_pairsum_multiplication_permutation import MinPairSumMultiplicationPermutation_ParameterController
from Gym.parameter_controllers.min_path_cover_dag import MinPathCover_DAG_ParameterController
from Gym.parameter_controllers.min_sum_chebyshev_distance import MinSumChebyshevDistance_ParameterController
from Gym.parameter_controllers.min_sum_distance_square import MinSumDistanceSquare_ParameterController
from Gym.parameter_controllers.min_sum_pre_xor import MinSumPreXor_ParameterController
from Gym.parameter_controllers.min_swap_two_permutations import MinSwapTwoPermutations_ParameterController
from Gym.parameter_controllers.min_xor_pair import MinXorPair_ParameterController
from Gym.parameter_controllers.minesweeping import Minesweeping_ParameterController
from Gym.parameter_controllers.minimal_cyclic_shift import MinimalCyclicShift_ParameterController
from Gym.parameter_controllers.minimum_chromatic_number import MinimumChromaticNumber_ParameterController
from Gym.parameter_controllers.minimum_chromatic_number_segment_overlap import MinimumChromaticNumber_SegmentOverlap_ParameterController
from Gym.parameter_controllers.minimum_cost_maximum_flow import MinimumCost_MaximumFlow_ParameterController
from Gym.parameter_controllers.minimum_crossing_edges_graph_partition import Minimum_CrossingEdges_GraphPartition_ParameterController
from Gym.parameter_controllers.minimum_directed_spanning_tree import MinimumDirectedSpanningTree_ParameterController
from Gym.parameter_controllers.minimum_dominating_interval import Minimum_DominatingInterval_ParameterController
from Gym.parameter_controllers.minimum_dominating_set import Minimum_DominatingSet_ParameterController
from Gym.parameter_controllers.minimum_dominating_set_grid import Minimum_DominatingSet_Grid_ParameterController
from Gym.parameter_controllers.minimum_fibonacci_representation import MinimumFibonacciRepresentation_ParameterController
from Gym.parameter_controllers.minimum_harmonious_chromatic_number import MinimumHarmoniousChromaticNumber_ParameterController
from Gym.parameter_controllers.minimum_interval_coverage import MinimumIntervalCoverage_ParameterController
from Gym.parameter_controllers.minimum_max_abs_slicer import Minimum_MaxAbsSlicer_ParameterController
from Gym.parameter_controllers.minimum_max_slicer import Minimum_MaxSlicer_ParameterController
from Gym.parameter_controllers.minimum_ratio_path import MinimumRatioPath_ParameterController
from Gym.parameter_controllers.minimum_spanning_tree import MinimumSpanningTree_ParameterController
from Gym.parameter_controllers.minimum_spanning_tree_counting import MinimumSpanningTreeCounting_ParameterController
from Gym.parameter_controllers.minimum_steiner_tree import MinimumSteinerTree_ParameterController
from Gym.parameter_controllers.minimum_sum_difference_submatrix import MinimumSumDifferenceSubmatrix_ParameterController
from Gym.parameter_controllers.minimum_tree_weighted_dominating_ancestor import MinimumTreeWeightedDominatingAncestor_ParameterController
from Gym.parameter_controllers.minimum_unconflicted_grid_kmax import MinimumUnconflictedGridKMax_ParameterController
from Gym.parameter_controllers.minimum_vertex_cover import Minimum_VertexCover_ParameterController
from Gym.parameter_controllers.minimum_weighted_spanning_tree import MinimumWeightedSpanningTree_ParameterController
from Gym.parameter_controllers.mitter_transportation import MitterTransportation_ParameterController
from Gym.parameter_controllers.mixed_graph_eulerian_circuit import MixedGraphEulerianCircuit_ParameterController
from Gym.parameter_controllers.money_charging_game import MoneyChargingGame_ParameterController
from Gym.parameter_controllers.monochrome_block_counting import MonochromeBlockCounting_ParameterController
from Gym.parameter_controllers.monotonic_stack import MonotonicStack_ParameterController
from Gym.parameter_controllers.most_component_tree_removing_two_paths import MostComponentTreeRemovingTwoPaths_ParameterController
from Gym.parameter_controllers.most_num_edge_non_self_isomorphism import MostNumEdge_NonSelfIsomorphism_ParameterController
from Gym.parameter_controllers.multidrink import MultiDrink_ParameterController
from Gym.parameter_controllers.multiple_flipping_game import MultipleFlippingGame_ParameterController
from Gym.parameter_controllers.multiplication import Multiplication_ParameterController
from Gym.parameter_controllers.myj import MYJ_ParameterController
from Gym.parameter_controllers.nand_result_counting import NANDResultCounting_ParameterController
from Gym.parameter_controllers.negative_base import NegativeBase_ParameterController
from Gym.parameter_controllers.new_nim_game import NewNimGame_ParameterController
from Gym.parameter_controllers.next_palindromic import NextPalindromic_ParameterController
from Gym.parameter_controllers.nine_puzzle import NinePuzzle_ParameterController
from Gym.parameter_controllers.no_adjacent_girl_counting import NoAdjacentGirlCounting_ParameterController
from Gym.parameter_controllers.no_double_triple_counting import NoDoubleTripleCounting_ParameterController
from Gym.parameter_controllers.not_containing_string_counting import NotContainingStringCounting_ParameterController
from Gym.parameter_controllers.number_partition_counting import NumberPartitionCounting_ParameterController
from Gym.parameter_controllers.numbrix import Numbrix_ParameterController
from Gym.parameter_controllers.odd_visitation import OddVisitation_ParameterController
from Gym.parameter_controllers.odl_distance import ODLDistance_ParameterController
from Gym.parameter_controllers.pair_more_one_counting import PairMoreOneCounting_ParameterController
from Gym.parameter_controllers.palembang_bridges import PalembangBridges_ParameterController
from Gym.parameter_controllers.palindrome_partition_counting import PalindromePartitionCounting_ParameterController
from Gym.parameter_controllers.palindromic_substring_number_counting import PalindromicSubstringNumberCounting_ParameterController
from Gym.parameter_controllers.pan_solar_panels import PanSolarPanels_ParameterController
from Gym.parameter_controllers.path_no_going_back_counting import Path_NoGoingBack_Counting_ParameterController
from Gym.parameter_controllers.patrol import Patrol_ParameterController
from Gym.parameter_controllers.pcp_permutation import PCPPermutation_ParameterController
from Gym.parameter_controllers.pipeline_arrangement import PipelineArrangement_ParameterController
from Gym.parameter_controllers.pol_polarization import POLPolarization_ParameterController
from Gym.parameter_controllers.polya_model import PolyaModel_ParameterController
from Gym.parameter_controllers.polynomial_factorization import PolynomialFactorization_ParameterController
from Gym.parameter_controllers.polynomial_interpolation import PolynomialInterpolation_ParameterController
from Gym.parameter_controllers.polynomial_minimum import PolynomialMinimum_ParameterController
from Gym.parameter_controllers.polynomial_remainder import PolynomialRemainder_ParameterController
from Gym.parameter_controllers.power_cycle import PowerCycle_ParameterController
from Gym.parameter_controllers.power_shortcut import PowerShortcut_ParameterController
from Gym.parameter_controllers.powernest import PowerNest_ParameterController
from Gym.parameter_controllers.prefix_concatenation import PrefixConcatenation_ParameterController
from Gym.parameter_controllers.prefix_product_mod_distinct_permutation import PrefixProductMODDistinctPermutation_ParameterController
from Gym.parameter_controllers.prefix_sum_mod_distinct_permutation import PrefixSumMODDistinctPermutation_ParameterController
from Gym.parameter_controllers.prefixuffix import Prefixuffix_ParameterController
from Gym.parameter_controllers.preorder_traversal import PreorderTraversal_ParameterController
from Gym.parameter_controllers.prime_graph_minimum_chromatic_number import PrimeGraph_MinimumChromaticNumber_ParameterController
from Gym.parameter_controllers.protecting_flowers import ProtectingFlowers_ParameterController
from Gym.parameter_controllers.pythagorean_graph_independent_set_counting import PythagoreanGraph_IndependentSetCounting_ParameterController
from Gym.parameter_controllers.quad_magic_items import QuadMagicItems_ParameterController
from Gym.parameter_controllers.quadratic_function_segmentation import QuadraticFunctionSegmentation_ParameterController
from Gym.parameter_controllers.quantum_lock_puzzle import QuantumLockPuzzle_ParameterController
from Gym.parameter_controllers.queen_placement import QueenPlacement_ParameterController
from Gym.parameter_controllers.random_range_max_expectation import RandomRangeMaxExpectation_ParameterController
from Gym.parameter_controllers.range_constrained_increasing_sequence_counting import RangeConstrained_IncreasingSequence_Counting_ParameterController
from Gym.parameter_controllers.range_four_sequence_construction import RangeFourSequenceConstruction_ParameterController
from Gym.parameter_controllers.range_shrinking_sequence_counting import RangeShrinkingSequenceCounting_ParameterController
from Gym.parameter_controllers.recursive_function import RecursiveFunction_ParameterController
from Gym.parameter_controllers.recursive_sequence_sum_construction import RecursiveSequenceSumConstruction_ParameterController
from Gym.parameter_controllers.repeat_sequence_lnds import RepeatSequenceLNDS_ParameterController
from Gym.parameter_controllers.root_extraction import RootExtraction_ParameterController
from Gym.parameter_controllers.round_robin import RoundRobin_ParameterController
from Gym.parameter_controllers.roundtable_assignment import RoundTableAssignment_ParameterController
from Gym.parameter_controllers.royal_lock_counting import RoyalLockCounting_ParameterController
from Gym.parameter_controllers.salad_bar import SaladBar_ParameterController
from Gym.parameter_controllers.salesman_fatigue import SalesmanFatigue_ParameterController
from Gym.parameter_controllers.same_adjacency_counting import SameAdjacencyCounting_ParameterController
from Gym.parameter_controllers.sat import SAT_ParameterController
from Gym.parameter_controllers.scc_sequence_counting import SCC_Sequence_Counting_ParameterController
from Gym.parameter_controllers.secret_cow_code import SecretCowCode_ParameterController
from Gym.parameter_controllers.segment_min_length_equal_counting import SegmentMinLengthEqual_Counting_ParameterController
from Gym.parameter_controllers.segment_tree_sorting_counting import SegmentTreeSortingCounting_ParameterController
from Gym.parameter_controllers.self_power_sequence_mod import SelfPowerSequenceMOD_ParameterController
from Gym.parameter_controllers.set_cover import SetCover_ParameterController
from Gym.parameter_controllers.set_splitting import SetSplitting_ParameterController
from Gym.parameter_controllers.shared_substring_counting import SharedSubstringCounting_ParameterController
from Gym.parameter_controllers.shortest_path import ShortestPath_ParameterController
from Gym.parameter_controllers.shortest_path_count_construction import ShortestPathCountConstruction_ParameterController
from Gym.parameter_controllers.shortest_unicolor_substring import ShortestUnicolorSubstring_ParameterController
from Gym.parameter_controllers.singing_girl_story import SingingGirlStory_ParameterController
from Gym.parameter_controllers.single_stack_sorting import SingleStackSorting_ParameterController
from Gym.parameter_controllers.ska_rock_garden import SkaRockGarden_ParameterController
from Gym.parameter_controllers.skyscraper_puzzle import SkyscraperPuzzle_ParameterController
from Gym.parameter_controllers.skyscraper_sum_puzzle import SkyscraperSumPuzzle_ParameterController
from Gym.parameter_controllers.sliding_window import SlidingWindow_ParameterController
from Gym.parameter_controllers.slo_elephants import SLOElephants_ParameterController
from Gym.parameter_controllers.smallest_binary_multiple import SmallestBinaryMultiple_ParameterController
from Gym.parameter_controllers.smallest_circle import SmallestCircle_ParameterController
from Gym.parameter_controllers.sorting import Sorting_ParameterController
from Gym.parameter_controllers.spiral_matrix import SpiralMatrix_ParameterController
from Gym.parameter_controllers.splitting_game import SplittingGame_ParameterController
from Gym.parameter_controllers.spy_network import SpyNetwork_ParameterController
from Gym.parameter_controllers.squ_squarks import SquSquarks_ParameterController
from Gym.parameter_controllers.square_undamaged_point_counting import SquareUndamagedPointCounting_ParameterController
from Gym.parameter_controllers.star_battle import StarBattle_ParameterController
from Gym.parameter_controllers.stirling_second import StirlingSecond_ParameterController
from Gym.parameter_controllers.stone_game import StoneGame_ParameterController
from Gym.parameter_controllers.stone_intervals_game import StoneIntervalsGame_ParameterController
from Gym.parameter_controllers.string_partition_shuffle import StringPartitionShuffle_ParameterController
from Gym.parameter_controllers.string_reversal_construction import StringReversalConstruction_ParameterController
from Gym.parameter_controllers.stu_well import STUWell_ParameterController
from Gym.parameter_controllers.stunt_flying import StuntFlying_ParameterController
from Gym.parameter_controllers.subarray_sum_xor import SubarraySumXor_ParameterController
from Gym.parameter_controllers.subarray_xor_sum import SubarrayXorSum_ParameterController
from Gym.parameter_controllers.subgraph_isomorphism import SubgraphIsomorphism_ParameterController
from Gym.parameter_controllers.submatrix_sum_divisible_counting import SubmatrixSumDivisibleCounting_ParameterController
from Gym.parameter_controllers.subsequence_reversal_lnds import SubsequenceReversalLNDS_ParameterController
from Gym.parameter_controllers.subset_sum import SubsetSum_ParameterController
from Gym.parameter_controllers.subset_sum_sequence import SubsetSumSequence_ParameterController
from Gym.parameter_controllers.sudoku import Sudoku_ParameterController
from Gym.parameter_controllers.sum_divisor_num import Sum_DivisorNum_ParameterController
from Gym.parameter_controllers.sum_gcd import SumGCD_ParameterController
from Gym.parameter_controllers.sum_gcd_with_individual import SumGCDWithIndividual_ParameterController
from Gym.parameter_controllers.sum_lcm import SumLCM_ParameterController
from Gym.parameter_controllers.sum_manhattan_curved_surface import SumManhattan_CurvedSurface_ParameterController
from Gym.parameter_controllers.sum_mod import SumMOD_ParameterController
from Gym.parameter_controllers.sum_phi_interval import SumPHIInterval_ParameterController
from Gym.parameter_controllers.sum_product_divisor_num import SumProductDivisorNum_ParameterController
from Gym.parameter_controllers.sum_pseudo_euclidean import SumPseudoEuclidean_ParameterController
from Gym.parameter_controllers.sum_set_multiplication import SumSetMultiplication_ParameterController
from Gym.parameter_controllers.sum_spanning_tree_gcd import SumSpanningTreeGCD_ParameterController
from Gym.parameter_controllers.sum_triangle_area import SumTriangleArea_ParameterController
from Gym.parameter_controllers.sum_xor_divisor_num import SumXorDivisorNum_ParameterController
from Gym.parameter_controllers.survo_puzzle import SurvoPuzzle_ParameterController
from Gym.parameter_controllers.taking_prime_game import TakingPrimeGame_ParameterController
from Gym.parameter_controllers.task_arrangement import TaskArrangement_ParameterController
from Gym.parameter_controllers.tetris_attack import TetrisAttack_ParameterController
from Gym.parameter_controllers.three_string_common_subsequence_counting import ThreeStringCommonSubsequenceCounting_ParameterController
from Gym.parameter_controllers.three_vertex_cycle_counting import ThreeVertexCycleCounting_ParameterController
from Gym.parameter_controllers.topological_sort import TopologicalSort_ParameterController
from Gym.parameter_controllers.topological_sort_minimal_lexicographical_order import TopologicalSort_MinimalLexicographicalOrder_ParameterController
from Gym.parameter_controllers.tournament_longest_path import Tournament_LongestPath_ParameterController
from Gym.parameter_controllers.transmission_delay import TransmissionDelay_ParameterController
from Gym.parameter_controllers.tree_add_one_edge_diameter import TreeAddOneEdgeDiameter_ParameterController
from Gym.parameter_controllers.tree_center import TreeCenter_ParameterController
from Gym.parameter_controllers.tree_change_one_edge_diameter import TreeChangeOneEdgeDiameter_ParameterController
from Gym.parameter_controllers.tree_coloring import TreeColoring_ParameterController
from Gym.parameter_controllers.tree_distance_equal_triad_counting import Tree_DistanceEqualTriad_Counting_ParameterController
from Gym.parameter_controllers.tree_dynamic_xor_zero_path import TreeDynamic_XORZeroPath_ParameterController
from Gym.parameter_controllers.tree_elimination_expectation import TreeElimination_Expectation_ParameterController
from Gym.parameter_controllers.tree_even_partitioning import TreeEvenPartitioning_ParameterController
from Gym.parameter_controllers.tree_maximum_visited_vertex import TreeMaximumVisitedVertex_ParameterController
from Gym.parameter_controllers.tree_random_walk_expectation import TreeRandomWalkExpectation_ParameterController
from Gym.parameter_controllers.tree_topological_sequence_counting import TreeTopologicalSequenceCounting_ParameterController
from Gym.parameter_controllers.triumphal_arch import TriumphalArch_ParameterController
from Gym.parameter_controllers.twiddle_puzzle import TwiddlePuzzle_ParameterController
from Gym.parameter_controllers.two_sat import TwoSAT_ParameterController
from Gym.parameter_controllers.two_set_all_coprime_counting import TwoSet_AllCoprime_Counting_ParameterController
from Gym.parameter_controllers.undamaged_submatrix_counting import UndamagedSubmatrixCounting_ParameterController
from Gym.parameter_controllers.value_diminishing_selection import ValueDiminishingSelection_ParameterController
from Gym.parameter_controllers.vertex_k_center import Vertex_KCenter_ParameterController
from Gym.parameter_controllers.virus_synthesis import VirusSynthesis_ParameterController
from Gym.parameter_controllers.visible_line import VisibleLine_ParameterController
from Gym.parameter_controllers.warehouse_construction import WarehouseConstruction_ParameterController
from Gym.parameter_controllers.weighted_binarytree import WeightedBinaryTree_ParameterController
from Gym.parameter_controllers.weighted_lis import WeightedLIS_ParameterController
from Gym.parameter_controllers.whack_a_mole import WhackAMole_ParameterController
from Gym.parameter_controllers.wil import WIL_ParameterController
from Gym.parameter_controllers.wyc import WYC_ParameterController
from Gym.parameter_controllers.wyr_leveling_ground import WYRLevelingGround_ParameterController
from Gym.parameter_controllers.xor_equation_counting import XorEquationCounting_ParameterController
from Gym.parameter_controllers.zero_prefix_subset_counting import ZeroPrefixSubsetCounting_ParameterController


identifier2controller = {
    "ABProgramSimulation" : ABProgramSimulation_ParameterController,
    "AddMultiple_Divisible_Counting" : AddMultiple_Divisible_Counting_ParameterController,
    "AdditionTable" : AdditionTable_ParameterController,
    "AlmostCompleteGraphCycleCounting" : AlmostCompleteGraphCycleCounting_ParameterController,
    "AndOr_Sequence_Counting" : AndOr_Sequence_Counting_ParameterController,
    "AntiPalindromicSubstringCounting" : AntiPalindromicSubstringCounting_ParameterController,
    "Axis_KCenter" : Axis_KCenter_ParameterController,
    "BAJBytecomputer" : BAJBytecomputer_ParameterController,
    "BannedPointSupersetPathCounting" : BannedPointSupersetPathCounting_ParameterController,
    "BanyanHeart" : BanyanHeart_ParameterController,
    "BEZMinimalistSecurity" : BEZMinimalistSecurity_ParameterController,
    "BezoutIdentity" : BezoutIdentity_ParameterController,
    "Binario" : Binario_ParameterController,
    "Binario_NoAdjacencyRequirement" : Binario_NoAdjacencyRequirement_ParameterController,
    "BinaryAlternation" : BinaryAlternation_ParameterController,
    "BinaryStringNoAdjacentCount" : BinaryStringNoAdjacentCount_ParameterController,
    "binary_string_no_adjacent_count" : BinaryStringNoAdjacentCount_ParameterController,
    "BinaryLinearEquation_SolutionCounting" : BinaryLinearEquation_SolutionCounting_ParameterController,
    "BinaryTreeLeafNumExpectation" : BinaryTreeLeafNumExpectation_ParameterController,
    "BitEquationCounting" : BitEquationCounting_ParameterController,
    "BitAndZero_PathCounting" : BitAndZero_PathCounting_ParameterController,
    "BitwiseOperationSequenceCounting" : BitwiseOperationSequenceCounting_ParameterController,
    "BlockImage" : BlockImage_ParameterController,
    "BoundedAdjacencyDifference_Permutation_Counting" : BoundedAdjacencyDifference_Permutation_Counting_ParameterController,
    "BoundedIntervalIntersection" : BoundedIntervalIntersection_ParameterController,
    "BoundedMeanSubarrayCounting" : BoundedMeanSubarrayCounting_ParameterController,
    "BoundedSubarrayCounting" : BoundedSubarrayCounting_ParameterController,
    "BoxScheduling" : BoxScheduling_ParameterController,
    "Bridge" : Bridge_ParameterController,
    "BubbleSwapLowerBound_PermutationCounting" : BubbleSwapLowerBound_PermutationCounting_ParameterController,
    "BucketSorting" : BucketSorting_ParameterController,
    "CampfireParty" : CampfireParty_ParameterController,
    "CampsitePuzzle" : CampsitePuzzle_ParameterController,
    "Canon" : Canon_ParameterController,
    "CantorExpansion" : CantorExpansion_ParameterController,
    "CapitalCityEffect" : CapitalCityEffect_ParameterController,
    "CardColoringCounting" : CardColoringCounting_ParameterController,
    "CatalanNumberMod" : CatalanNumberMod_ParameterController,
    "CheckAllCycleXorZero" : CheckAllCycleXorZero_ParameterController,
    "ChoHamsters" : ChoHamsters_ParameterController,
    "Cinema" : Cinema_ParameterController,
    "Circuit" : Circuit_ParameterController,
    "CirculatingDecimalCounting" : CirculatingDecimalCounting_ParameterController,
    "CirculatingGrid" : CirculatingGrid_ParameterController,
    "CleaningUp" : CleaningUp_ParameterController,
    "ClearSymmetry" : ClearSymmetry_ParameterController,
    "Clique_IndependentSet_Partitioning_Counting" : Clique_IndependentSet_Partitioning_Counting_ParameterController,
    "CoinSquareGame" : CoinSquareGame_ParameterController,
    "ColoringCounting" : ColoringCounting_ParameterController,
    "CombinationOddSubsequenceCounting" : CombinationOddSubsequenceCounting_ParameterController,
    "ConcatenationPartitionCountingSum" : ConcatenationPartitionCountingSum_ParameterController,
    "CongruentEquation" : CongruentEquation_ParameterController,
    "ConstructHackInterval" : ConstructHackInterval_ParameterController,
    "ConvexHull" : ConvexHull_ParameterController,
    "Cornfield" : Cornfield_ParameterController,
    "CountdownEqual": Countdown_ParameterController, "CountdownClose": Countdown_ParameterController,
    "CowDanceShow" : CowDanceShow_ParameterController,
    "CRT" : CRT_ParameterController,
    "Cryptarithmetic" : Cryptarithmetic_ParameterController,
    "Cube_FixedLocalMaximumCounting" : Cube_FixedLocalMaximumCounting_ParameterController,
    "CycleCounting" : CycleCounting_ParameterController,
    "DecreasingDigitCounting" : DecreasingDigitCounting_ParameterController,
    "DegreeFixed_SpanningTree" : DegreeFixed_SpanningTree_ParameterController,
    "DeltaMinPopcount" : DeltaMinPopcount_ParameterController,
    "DeltaNimGame" : DeltaNimGame_ParameterController,
    "DerangementExtension" : DerangementExtension_ParameterController,
    "DifferenceConstraintSystem" : DifferenceConstraintSystem_ParameterController,
    "DifferenceConstraintSystemDAG" : DifferenceConstraintSystemDAG_ParameterController,
    "DifferentColorPairing" : DifferentColorPairing_ParameterController,
    "Differentiate" : Differentiate_ParameterController,
    "DigitLISCounting" : DigitLISCounting_ParameterController,
    "DigitSumInterval" : DigitSumInterval_ParameterController,
    "digit_sum_interval" : DigitSumInterval_ParameterController,
    "DiscreteLogarithm" : DiscreteLogarithm_ParameterController,
    "Disinfection" : Disinfection_ParameterController,
    "DistinctArrayPermutation" : DistinctArrayPermutation_ParameterController,
    "DistinctEdgeColoredCompleteGraphCounting" : DistinctEdgeColoredCompleteGraphCounting_ParameterController,
    "Division" : Division_ParameterController,
    "DivisorFlipExpectation" : DivisorFlipExpectation_ParameterController,
    "DoubleCrossCounting" : DoubleCrossCounting_ParameterController,
    "DoublePalindromicStringCounting" : DoublePalindromicStringCounting_ParameterController,
    "DoubleStackSorting" : DoubleStackSorting_ParameterController,
    "DynDynamite" : DynDynamite_ParameterController,
    "EightDigitPuzzle" : EightDigitPuzzle_ParameterController,
    "EmperorWorries" : EmperorWorries_ParameterController,
    "EnergyStorageMeter" : EnergyStorageMeter_ParameterController,
    "EuclidGame" : EuclidGame_ParameterController,
    "EvenDegreeGraphPartitioning" : EvenDegreeGraphPartitioning_ParameterController,
    "Expression_AddingParenthese_Counting" : Expression_AddingParenthese_Counting_ParameterController,
    "FaceRightWay" : FaceRightWay_ParameterController,
    "FactorialTrailingZeroCount" : FactorialTrailingZeroCount_ParameterController,
    "FBI_BinaryTree" : FBI_BinaryTree_ParameterController,
    "Fibonacci" : Fibonacci_ParameterController,
    "FibonacciContainingCounting" : FibonacciContainingCounting_ParameterController,
    "Fibtrain" : Fibtrain_ParameterController,
    "FireworkShow" : FireworkShow_ParameterController,
    "FixedModK_Selection_Counting" : FixedModK_Selection_Counting_ParameterController,
    "FixedOneEdgeNum_SpanningTree" : FixedOneEdgeNum_SpanningTree_ParameterController,
    "FractionalProgramming" : FractionalProgramming_ParameterController,
    "FractionalProgramming_BipartiteGraphMatching" : FractionalProgramming_BipartiteGraphMatching_ParameterController,
    "FutoshikiPuzzle" : FutoshikiPuzzle_ParameterController,
    "GasFireExtinguishers" : GasFireExtinguishers_ParameterController,
    "GaussianElimination" : GaussianElimination_ParameterController,
    "GCDFibonacciProduct" : GCDFibonacciProduct_ParameterController,
    "GcdLcmCounting" : GcdLcmCounting_ParameterController,
    "GCDOne_Counting" : GCDOne_Counting_ParameterController,
    "GCDPrime_Counting" : GCDPrime_Counting_ParameterController,
    "GoldWashing" : GoldWashing_ParameterController,
    "GraMinimaGame" : GraMinimaGame_ParameterController,
    "GradeRankingCounting" : GradeRankingCounting_ParameterController,
    "GraphContainTreeCounting" : GraphContainTreeCounting_ParameterController,
    "GraphIsomorphism" : GraphIsomorphism_ParameterController,
    "GridBFS" : GridBFS_ParameterController,
    "GridColoringCounting" : GridColoringCounting_ParameterController,
    "GridComponent" : GridComponent_ParameterController,
    "GridLocalMinimumCounting" : GridLocalMinimumCounting_ParameterController,
    "GridPathCountingWithBlocks" : GridPathCountingWithBlocks_ParameterController,
    "grid_path_counting_with_blocks" : GridPathCountingWithBlocks_ParameterController,
    "GridParityConstruction" : GridParityConstruction_ParameterController,
    "GridTriangleCounting" : GridTriangleCounting_ParameterController,
    "HalvingChainCounting" : HalvingChainCounting_ParameterController,
    "HamiltonianPath" : HamiltonianPath_ParameterController,
    "HamiltonianPathExistence" : HamiltonianPathExistence_ParameterController,
    "HeapCounting" : HeapCounting_ParameterController,
    "HitoriPuzzle" : HitoriPuzzle_ParameterController,
    "HungryRabbit" : HungryRabbit_ParameterController,
    "HURWarehouseStore" : HURWarehouseStore_ParameterController,
    "ImpParty" : ImpParty_ParameterController,
    "IndividualSumBounded_SequenceCounting" : IndividualSumBounded_SequenceCounting_ParameterController,
    "IntegerFactorizationCounting" : IntegerFactorizationCounting_ParameterController,
    "IntegerProgramming" : IntegerProgramming_ParameterController,
    "Integral" : Integral_ParameterController,
    "InversionPair" : InversionPair_ParameterController,
    "InversionPairK_Counting" : InversionPairK_Counting_ParameterController,
    "Josephus" : Josephus_ParameterController,
    "JugPuzzle" : JugPuzzle_ParameterController,
    "KPartition" : KPartition_ParameterController,
    "Kakurasu" : Kakurasu_ParameterController,
    "KiddingMe" : KiddingMe_ParameterController,
    "KingSorting" : KingSorting_ParameterController,
    "KloBlocks" : KloBlocks_ParameterController,
    "Knapsack" : Knapsack_ParameterController,
    "KnightsAndKnaves" : KnightsAndKnaves_ParameterController,
    "KosDicing" : KosDicing_ParameterController,
    "Kth_BinaryTree" : Kth_BinaryTree_ParameterController,
    "Kth_SemiBalancedBracketSequence" : Kth_SemiBalancedBracketSequence_ParameterController,
    "KthSubsequence" : KthSubsequence_ParameterController,
    "KUR" : KUR_ParameterController,
    "LampChanging" : LampChanging_ParameterController,
    "LandAcquisition" : LandAcquisition_ParameterController,
    "LandformGenerationCounting" : LandformGenerationCounting_ParameterController,
    "LargestConvexPolygon" : LargestConvexPolygon_ParameterController,
    "LargestRectangle_AmongPoints" : LargestRectangle_AmongPoints_ParameterController,
    "LAS" : LAS_ParameterController,
    "LASLaser" : LASLaser_ParameterController,
    "LCM" : LCM_ParameterController,
    "LDSTwo_Counting" : LDSTwo_Counting_ParameterController,
    "LightUpPuzzle" : LightUpPuzzle_ParameterController,
    "LinkBeads" : LinkBeads_ParameterController,
    "LIS_LDS_Concatenation" : LIS_LDS_Concatenation_ParameterController,
    "LIZ_Lollipop" : LIZ_Lollipop_ParameterController,
    "Longest_DoublePalindrome" : Longest_DoublePalindrome_ParameterController,
    "Longest_MatchingSubsequence" : Longest_MatchingSubsequence_ParameterController,
    "LongestMaxDiffBoundedInterval" : LongestMaxDiffBoundedInterval_ParameterController,
    "LongestPath" : LongestPath_ParameterController,
    "Longest_RepeatedPalindrome" : Longest_RepeatedPalindrome_ParameterController,
    "MafMafia" : MafMafia_ParameterController,
    "MagicSquarePuzzle" : MagicSquarePuzzle_ParameterController,
    "MakingGrade" : MakingGrade_ParameterController,
    "Matrix_BinaryExponentiation" : Matrix_BinaryExponentiation_ParameterController,
    "MatrixPermutation_BothDiagonalOne" : MatrixPermutation_BothDiagonalOne_ParameterController,
    "MatrixPermutationEquivalence" : MatrixPermutationEquivalence_ParameterController,
    "MatrixPermutation_MainDiagonalOne" : MatrixPermutation_MainDiagonalOne_ParameterController,
    "MatrixPooling" : MatrixPooling_ParameterController,
    "MatrixRMQCounting" : MatrixRMQCounting_ParameterController,
    "MaxDifferentGroupPairDivision" : MaxDifferentGroupPairDivision_ParameterController,
    "MaxGridPathIntersection" : MaxGridPathIntersection_ParameterController,
    "MaxMinimum_AfterIntervalAddition" : MaxMinimum_AfterIntervalAddition_ParameterController,
    "MaxMultSplit" : MaxMultSplit_ParameterController,
    "MaxMultiplicationFixedSum" : MaxMultiplicationFixedSum_ParameterController,
    "MaxNoConflictingBombs" : MaxNoConflictingBombs_ParameterController,
    "Max_NonAdjacent_KElementSum" : Max_NonAdjacent_KElementSum_ParameterController,
    "MaxPermutation" : MaxPermutation_ParameterController,
    "MaxRMQExpectation" : MaxRMQExpectation_ParameterController,
    "MaxSegmentCoverageConstraint" : MaxSegmentCoverageConstraint_ParameterController,
    "MaxSumLDS" : MaxSumLDS_ParameterController,
    "MaxThreeSquareSum" : MaxThreeSquareSum_ParameterController,
    "Max_TreeConstrainedPermutation_Weight" : Max_TreeConstrainedPermutation_Weight_ParameterController,
    "MaxTree_KPathCoverage" : MaxTree_KPathCoverahe_ParameterController,
    "MaxTreeXorPath" : MaxTreeXorPath_ParameterController,
    "MaxWeightPalindromicSubstring" : MaxWeightPalindromicSubstring_ParameterController,
    "MaxXorPath" : MaxXorPath_ParameterController,
    "MaxXorSet" : MaxXorSet_ParameterController,
    "MaximumAchromaticNumber" : MaximumAchromaticNumber_ParameterController,
    "MaximumClique" : MaximumClique_ParameterController,
    "MaximumDivisor" : MaximumDivisor_ParameterController,
    "MaximumIndependentSetGrid" : MaximumIndependentSetGrid_ParameterController,
    "Maximum_IndependentSet_Tree" : Maximum_IndependentSet_Tree_ParameterController,
    "MaximumLexicographicalOrderSubsequence" : MaximumLexicographicalOrderSubsequence_ParameterController,
    "MaximumPointSegmentMatching" : MaximumPointSegmentMatching_ParameterController,
    "Maximum_SubsequenceNum" : Maximum_SubsequenceNum_ParameterController,
    "MaximumWeightMatching" : MaximumWeightMatching_ParameterController,
    "Maze" : Maze_ParameterController,
    "MinConversionToCycleCost" : MinConversionToCycleCost_ParameterController,
    "MinCostReducingLNDS" : MinCostReducingLNDS_ParameterController,
    "MinCostTreeCoverage" : MinCostTreeCoverage_ParameterController,
    "MinCubeAssignment" : MinCubeAssignment_ParameterController,
    "MinDivisionSumXor" : MinDivisionSumXor_ParameterController,
    "MinInorderBinaryTree" : MinInorderBinaryTree_ParameterController,
    "MinKDivisorNumber" : MinKDivisorNumber_ParameterController,
    "MinNoSolutionLinearDiophantineEquation" : MinNoSolutionLinearDiophantineEquation_ParameterController,
    "MinNonsubstring" : MinNonsubstring_ParameterController,
    "MinPairSumMultiplicationPermutation" : MinPairSumMultiplicationPermutation_ParameterController,
    "MinPathCover_DAG" : MinPathCover_DAG_ParameterController,
    "MinSumChebyshevDistance" : MinSumChebyshevDistance_ParameterController,
    "MinSumDistanceSquare" : MinSumDistanceSquare_ParameterController,
    "MinSumPreXor" : MinSumPreXor_ParameterController,
    "MinSwapTwoPermutations" : MinSwapTwoPermutations_ParameterController,
    "MinXorPair" : MinXorPair_ParameterController,
    "Minesweeping" : Minesweeping_ParameterController,
    "MinimalCyclicShift" : MinimalCyclicShift_ParameterController,
    "MinimumChromaticNumber" : MinimumChromaticNumber_ParameterController,
    "MinimumChromaticNumber_SegmentOverlap" : MinimumChromaticNumber_SegmentOverlap_ParameterController,
    "MinimumCost_MaximumFlow" : MinimumCost_MaximumFlow_ParameterController,
    "Minimum_CrossingEdges_GraphPartition" : Minimum_CrossingEdges_GraphPartition_ParameterController,
    "MinimumDirectedSpanningTree" : MinimumDirectedSpanningTree_ParameterController,
    "Minimum_DominatingInterval" : Minimum_DominatingInterval_ParameterController,
    "Minimum_DominatingSet" : Minimum_DominatingSet_ParameterController,
    "Minimum_DominatingSet_Grid" : Minimum_DominatingSet_Grid_ParameterController,
    "MinimumFibonacciRepresentation" : MinimumFibonacciRepresentation_ParameterController,
    "MinimumHarmoniousChromaticNumber" : MinimumHarmoniousChromaticNumber_ParameterController,
    "MinimumIntervalCoverage" : MinimumIntervalCoverage_ParameterController,
    "Minimum_MaxAbsSlicer" : Minimum_MaxAbsSlicer_ParameterController,
    "Minimum_MaxSlicer" : Minimum_MaxSlicer_ParameterController,
    "MinimumRatioPath" : MinimumRatioPath_ParameterController,
    "MinimumSpanningTree" : MinimumSpanningTree_ParameterController,
    "MinimumSpanningTreeCounting" : MinimumSpanningTreeCounting_ParameterController,
    "MinimumSteinerTree" : MinimumSteinerTree_ParameterController,
    "MinimumSumDifferenceSubmatrix" : MinimumSumDifferenceSubmatrix_ParameterController,
    "MinimumTreeWeightedDominatingAncestor" : MinimumTreeWeightedDominatingAncestor_ParameterController,
    "MinimumUnconflictedGridKMax" : MinimumUnconflictedGridKMax_ParameterController,
    "Minimum_VertexCover" : Minimum_VertexCover_ParameterController,
    "MinimumWeightedSpanningTree" : MinimumWeightedSpanningTree_ParameterController,
    "MitterTransportation" : MitterTransportation_ParameterController,
    "MixedGraphEulerianCircuit" : MixedGraphEulerianCircuit_ParameterController,
    "MoneyChargingGame" : MoneyChargingGame_ParameterController,
    "MonochromeBlockCounting" : MonochromeBlockCounting_ParameterController,
    "MonotonicStack" : MonotonicStack_ParameterController,
    "MostComponentTreeRemovingTwoPaths" : MostComponentTreeRemovingTwoPaths_ParameterController,
    "MostNumEdge_NonSelfIsomorphism" : MostNumEdge_NonSelfIsomorphism_ParameterController,
    "MultiDrink" : MultiDrink_ParameterController,
    "MultipleFlippingGame" : MultipleFlippingGame_ParameterController,
    "Multiplication" : Multiplication_ParameterController,
    "MYJ" : MYJ_ParameterController,
    "NANDResultCounting" : NANDResultCounting_ParameterController,
    "NegativeBase" : NegativeBase_ParameterController,
    "NewNimGame" : NewNimGame_ParameterController,
    "NextPalindromic" : NextPalindromic_ParameterController,
    "NinePuzzle" : NinePuzzle_ParameterController,
    "NoAdjacentGirlCounting" : NoAdjacentGirlCounting_ParameterController,
    "NoDoubleTripleCounting" : NoDoubleTripleCounting_ParameterController,
    "NotContainingStringCounting" : NotContainingStringCounting_ParameterController,
    "NumberPartitionCounting" : NumberPartitionCounting_ParameterController,
    "Numbrix" : Numbrix_ParameterController,
    "OddVisitation" : OddVisitation_ParameterController,
    "ODLDistance" : ODLDistance_ParameterController,
    "PairMoreOneCounting" : PairMoreOneCounting_ParameterController,
    "PalembangBridges" : PalembangBridges_ParameterController,
    "PalindromePartitionCounting" : PalindromePartitionCounting_ParameterController,
    "PalindromicSubstringNumberCounting" : PalindromicSubstringNumberCounting_ParameterController,
    "PanSolarPanels" : PanSolarPanels_ParameterController,
    "Path_NoGoingBack_Counting" : Path_NoGoingBack_Counting_ParameterController,
    "Patrol" : Patrol_ParameterController,
    "PCPPermutation" : PCPPermutation_ParameterController,
    "PipelineArrangement" : PipelineArrangement_ParameterController,
    "POLPolarization" : POLPolarization_ParameterController,
    "PolyaModel" : PolyaModel_ParameterController,
    "PolynomialFactorization" : PolynomialFactorization_ParameterController,
    "PolynomialInterpolation" : PolynomialInterpolation_ParameterController,
    "PolynomialMinimum" : PolynomialMinimum_ParameterController,
    "PolynomialRemainder" : PolynomialRemainder_ParameterController,
    "PowerCycle" : PowerCycle_ParameterController,
    "PowerShortcut" : PowerShortcut_ParameterController,
    "PowerNest" : PowerNest_ParameterController,
    "PrefixConcatenation" : PrefixConcatenation_ParameterController,
    "PrefixProductMODDistinctPermutation" : PrefixProductMODDistinctPermutation_ParameterController,
    "PrefixSumMODDistinctPermutation" : PrefixSumMODDistinctPermutation_ParameterController,
    "Prefixuffix" : Prefixuffix_ParameterController,
    "PreorderTraversal" : PreorderTraversal_ParameterController,
    "PrimeGraph_MinimumChromaticNumber" : PrimeGraph_MinimumChromaticNumber_ParameterController,
    "ProtectingFlowers" : ProtectingFlowers_ParameterController,
    "PythagoreanGraph_IndependentSetCounting" : PythagoreanGraph_IndependentSetCounting_ParameterController,
    "QuadMagicItems" : QuadMagicItems_ParameterController,
    "QuadraticFunctionSegmentation" : QuadraticFunctionSegmentation_ParameterController,
    "QuantumLockPuzzle" : QuantumLockPuzzle_ParameterController,
    "QueenPlacement" : QueenPlacement_ParameterController,
    "RandomRangeMaxExpectation" : RandomRangeMaxExpectation_ParameterController,
    "RangeConstrained_IncreasingSequence_Counting" : RangeConstrained_IncreasingSequence_Counting_ParameterController,
    "RangeFourSequenceConstruction" : RangeFourSequenceConstruction_ParameterController,
    "RangeShrinkingSequenceCounting" : RangeShrinkingSequenceCounting_ParameterController,
    "RecursiveFunction" : RecursiveFunction_ParameterController,
    "RecursiveSequenceSumConstruction" : RecursiveSequenceSumConstruction_ParameterController,
    "RepeatSequenceLNDS" : RepeatSequenceLNDS_ParameterController,
    "RootExtraction" : RootExtraction_ParameterController,
    "RoundRobin" : RoundRobin_ParameterController,
    "RoundTableAssignment" : RoundTableAssignment_ParameterController,
    "RoyalLockCounting" : RoyalLockCounting_ParameterController,
    "SaladBar" : SaladBar_ParameterController,
    "SalesmanFatigue" : SalesmanFatigue_ParameterController,
    "SameAdjacencyCounting" : SameAdjacencyCounting_ParameterController,
    "SAT" : SAT_ParameterController,
    "SCC_Sequence_Counting" : SCC_Sequence_Counting_ParameterController,
    "SecretCowCode" : SecretCowCode_ParameterController,
    "SegmentMinLengthEqual_Counting" : SegmentMinLengthEqual_Counting_ParameterController,
    "SegmentTreeSortingCounting" : SegmentTreeSortingCounting_ParameterController,
    "SelfPowerSequenceMOD" : SelfPowerSequenceMOD_ParameterController,
    "SetCover" : SetCover_ParameterController,
    "SetSplitting" : SetSplitting_ParameterController,
    "SharedSubstringCounting" : SharedSubstringCounting_ParameterController,
    "ShortestPath" : ShortestPath_ParameterController,
    "ShortestPathCountConstruction" : ShortestPathCountConstruction_ParameterController,
    "ShortestUnicolorSubstring" : ShortestUnicolorSubstring_ParameterController,
    "SingingGirlStory" : SingingGirlStory_ParameterController,
    "SingleStackSorting" : SingleStackSorting_ParameterController,
    "SkaRockGarden" : SkaRockGarden_ParameterController,
    "SkyscraperPuzzle" : SkyscraperPuzzle_ParameterController,
    "SkyscraperSumPuzzle" : SkyscraperSumPuzzle_ParameterController,
    "SlidingWindow" : SlidingWindow_ParameterController,
    "SLOElephants" : SLOElephants_ParameterController,
    "SmallestBinaryMultiple" : SmallestBinaryMultiple_ParameterController,
    "SmallestCircle" : SmallestCircle_ParameterController,
    "Sorting" : Sorting_ParameterController,
    "SpiralMatrix" : SpiralMatrix_ParameterController,
    "SplittingGame" : SplittingGame_ParameterController,
    "SpyNetwork" : SpyNetwork_ParameterController,
    "SquSquarks" : SquSquarks_ParameterController,
    "SquareUndamagedPointCounting" : SquareUndamagedPointCounting_ParameterController,
    "StarBattle" : StarBattle_ParameterController,
    "StirlingSecond" : StirlingSecond_ParameterController,
    "StoneGame" : StoneGame_ParameterController,
    "StoneIntervalsGame" : StoneIntervalsGame_ParameterController,
    "StringPartitionShuffle" : StringPartitionShuffle_ParameterController,
    "StringReversalConstruction" : StringReversalConstruction_ParameterController,
    "STUWell" : STUWell_ParameterController,
    "StuntFlying" : StuntFlying_ParameterController,
    "SubarraySumXor" : SubarraySumXor_ParameterController,
    "SubarrayXorSum" : SubarrayXorSum_ParameterController,
    "SubgraphIsomorphism" : SubgraphIsomorphism_ParameterController,
    "SubmatrixSumDivisibleCounting" : SubmatrixSumDivisibleCounting_ParameterController,
    "SubsequenceReversalLNDS" : SubsequenceReversalLNDS_ParameterController,
    "SubsetSum" : SubsetSum_ParameterController,
    "SubsetSumSequence" : SubsetSumSequence_ParameterController,
    "Sudoku" : Sudoku_ParameterController,
    "Sum_DivisorNum" : Sum_DivisorNum_ParameterController,
    "SumGCD" : SumGCD_ParameterController,
    "SumGCDWithIndividual" : SumGCDWithIndividual_ParameterController,
    "SumLCM" : SumLCM_ParameterController,
    "SumManhattan_CurvedSurface" : SumManhattan_CurvedSurface_ParameterController,
    "SumMOD" : SumMOD_ParameterController,
    "SumPHIInterval" : SumPHIInterval_ParameterController,
    "SumProductDivisorNum" : SumProductDivisorNum_ParameterController,
    "SumPseudoEuclidean" : SumPseudoEuclidean_ParameterController,
    "SumSetMultiplication" : SumSetMultiplication_ParameterController,
    "SumSpanningTreeGCD" : SumSpanningTreeGCD_ParameterController,
    "SumTriangleArea" : SumTriangleArea_ParameterController,
    "SumXorDivisorNum" : SumXorDivisorNum_ParameterController,
    "SurvoPuzzle" : SurvoPuzzle_ParameterController,
    "TakingPrimeGame" : TakingPrimeGame_ParameterController,
    "TaskArrangement" : TaskArrangement_ParameterController,
    "TetrisAttack" : TetrisAttack_ParameterController,
    "ThreeStringCommonSubsequenceCounting" : ThreeStringCommonSubsequenceCounting_ParameterController,
    "ThreeVertexCycleCounting" : ThreeVertexCycleCounting_ParameterController,
    "TopologicalSort" : TopologicalSort_ParameterController,
    "TopologicalSort_MinimalLexicographicalOrder" : TopologicalSort_MinimalLexicographicalOrder_ParameterController,
    "Tournament_LongestPath" : Tournament_LongestPath_ParameterController,
    "TransmissionDelay" : TransmissionDelay_ParameterController,
    "TreeAddOneEdgeDiameter" : TreeAddOneEdgeDiameter_ParameterController,
    "TreeCenter" : TreeCenter_ParameterController,
    "TreeChangeOneEdgeDiameter" : TreeChangeOneEdgeDiameter_ParameterController,
    "TreeColoring" : TreeColoring_ParameterController,
    "Tree_DistanceEqualTriad_Counting" : Tree_DistanceEqualTriad_Counting_ParameterController,
    "TreeDynamic_XORZeroPath" : TreeDynamic_XORZeroPath_ParameterController,
    "TreeElimination_Expectation" : TreeElimination_Expectation_ParameterController,
    "TreeEvenPartitioning" : TreeEvenPartitioning_ParameterController,
    "TreeMaximumVisitedVertex" : TreeMaximumVisitedVertex_ParameterController,
    "TreeRandomWalkExpectation" : TreeRandomWalkExpectation_ParameterController,
    "TreeTopologicalSequenceCounting" : TreeTopologicalSequenceCounting_ParameterController,
    "TriumphalArch" : TriumphalArch_ParameterController,
    "TwiddlePuzzle" : TwiddlePuzzle_ParameterController,
    "TwoSAT" : TwoSAT_ParameterController,
    "TwoSet_AllCoprime_Counting" : TwoSet_AllCoprime_Counting_ParameterController,
    "UndamagedSubmatrixCounting" : UndamagedSubmatrixCounting_ParameterController,
    "ValueDiminishingSelection" : ValueDiminishingSelection_ParameterController,
    "Vertex_KCenter" : Vertex_KCenter_ParameterController,
    "VirusSynthesis" : VirusSynthesis_ParameterController,
    "VisibleLine" : VisibleLine_ParameterController,
    "WarehouseConstruction" : WarehouseConstruction_ParameterController,
    "WeightedBinaryTree" : WeightedBinaryTree_ParameterController,
    "WeightedLIS" : WeightedLIS_ParameterController,
    "WhackAMole" : WhackAMole_ParameterController,
    "WIL" : WIL_ParameterController,
    "WYC" : WYC_ParameterController,
    "WYRLevelingGround" : WYRLevelingGround_ParameterController,
    "XorEquationCounting" : XorEquationCounting_ParameterController,
    "ZeroPrefixSubsetCounting" : ZeroPrefixSubsetCounting_ParameterController,
}