from Gym.environments.ab_program_simulation import ABProgramSimulation_Environment
from Gym.environments.add_multiple_divisible_counting import AddMultiple_Divisible_Counting_Environment
from Gym.environments.addition_table import AdditionTable_Environment
from Gym.environments.almost_complete_graph_cycle_counting import AlmostCompleteGraphCycleCounting_Environment
from Gym.environments.and_or_sequence_counting import AndOr_Sequence_Counting_Environment
from Gym.environments.anti_palindromic_substring_counting import AntiPalindromicSubstringCounting_Environment
from Gym.environments.axis_k_center import Axis_KCenter_Environment
from Gym.environments.baj_bytecomputer import BAJBytecomputer_Environment
from Gym.environments.banned_point_superset_path_counting import BannedPointSupersetPathCounting_Environment
from Gym.environments.banyan_heart import BanyanHeart_Environment
from Gym.environments.bez_minimalist_security import BEZMinimalistSecurity_Environment
from Gym.environments.bezout_identity import BezoutIdentity_Environment
from Gym.environments.binario import Binario_Environment
from Gym.environments.binario_no_adjacency_requirement import Binario_NoAdjacencyRequirement_Environment
from Gym.environments.binary_alternation import BinaryAlternation_Environment
from Gym.environments.binary_string_no_adjacent_count import BinaryStringNoAdjacentCount_Environment
from Gym.environments.binary_linear_equation_solution_counting import BinaryLinearEquation_SolutionCounting_Environment
from Gym.environments.binary_tree_leaf_num_expectation import BinaryTreeLeafNumExpectation_Environment
from Gym.environments.bit_equation_counting import BitEquationCounting_Environment
from Gym.environments.bitand_zero_path_counting import BitAndZero_PathCounting_Environment
from Gym.environments.bitwise_operation_sequence_counting import BitwiseOperationSequenceCounting_Environment
from Gym.environments.block_image import BlockImage_Environment
from Gym.environments.bounded_adjacency_difference_permutation_counting import BoundedAdjacencyDifference_Permutation_Counting_Environment
from Gym.environments.bounded_interval_intersection import BoundedIntervalIntersection_Environment
from Gym.environments.bounded_mean_subarray_counting import BoundedMeanSubarrayCounting_Environment
from Gym.environments.bounded_subarray_counting import BoundedSubarrayCounting_Environment
from Gym.environments.box_scheduling import BoxScheduling_Environment
from Gym.environments.bridge import Bridge_Environment
from Gym.environments.bubble_swap_lower_bound_permutation_counting import BubbleSwapLowerBound_PermutationCounting_Environment
from Gym.environments.bucket_sorting import BucketSorting_Environment
from Gym.environments.campfire_party import CampfireParty_Environment
from Gym.environments.campsite_puzzle import CampsitePuzzle_Environment
from Gym.environments.canon import Canon_Environment
from Gym.environments.cantor_expansion import CantorExpansion_Environment
from Gym.environments.capital_city_effect import CapitalCityEffect_Environment
from Gym.environments.card_coloring_counting import CardColoringCounting_Environment
from Gym.environments.catalan_number_mod import CatalanNumberMod_Environment
from Gym.environments.check_all_cycle_xor_zero import CheckAllCycleXorZero_Environment
from Gym.environments.cho_hamsters import ChoHamsters_Environment
from Gym.environments.cinema import Cinema_Environment
from Gym.environments.circuit import Circuit_Environment
from Gym.environments.circulating_decimal_counting import CirculatingDecimalCounting_Environment
from Gym.environments.circulating_grid import CirculatingGrid_Environment
from Gym.environments.cleaning_up import CleaningUp_Environment
from Gym.environments.clear_symmetry import ClearSymmetry_Environment
from Gym.environments.clique_independent_set_partitioning_counting import Clique_IndependentSet_Partitioning_Counting_Environment
from Gym.environments.coin_square_game import CoinSquareGame_Environment
from Gym.environments.coloring_counting import ColoringCounting_Environment
from Gym.environments.combination_odd_subsequence_counting import CombinationOddSubsequenceCounting_Environment
from Gym.environments.concatenation_partition_counting_sum import ConcatenationPartitionCountingSum_Environment
from Gym.environments.congruent_equation import CongruentEquation_Environment
from Gym.environments.construct_hack_interval import ConstructHackInterval_Environment
from Gym.environments.convex_hull import ConvexHull_Environment
from Gym.environments.cornfield import Cornfield_Environment
from Gym.environments.countdown import CountdownEqual_Environment, CountdownClose_Environment
from Gym.environments.cow_dance_show import CowDanceShow_Environment
from Gym.environments.crt import CRT_Environment
from Gym.environments.cryptarithmetic import Cryptarithmetic_Environment
from Gym.environments.cube_fixed_local_maximum_counting import Cube_FixedLocalMaximumCounting_Environment
from Gym.environments.cycle_counting import CycleCounting_Environment
from Gym.environments.decreasing_digit_counting import DecreasingDigitCounting_Environment
from Gym.environments.degree_fixed_spanning_tree import DegreeFixed_SpanningTree_Environment
from Gym.environments.delta_min_popcount import DeltaMinPopcount_Environment
from Gym.environments.delta_nim_game import DeltaNimGame_Environment
from Gym.environments.derangement_extension import DerangementExtension_Environment
from Gym.environments.difference_constraint_system import DifferenceConstraintSystem_Environment
from Gym.environments.difference_constraint_system_dag import DifferenceConstraintSystemDAG_Environment
from Gym.environments.different_color_pairing import DifferentColorPairing_Environment
from Gym.environments.differentiate import Differentiate_Environment
from Gym.environments.digit_lis_counting import DigitLISCounting_Environment
from Gym.environments.digit_sum_interval import DigitSumInterval_Environment
from Gym.environments.discrete_logarithm import DiscreteLogarithm_Environment
from Gym.environments.disinfection import Disinfection_Environment
from Gym.environments.distinct_array_permutation import DistinctArrayPermutation_Environment
from Gym.environments.distinct_edge_colored_complete_graph_counting import DistinctEdgeColoredCompleteGraphCounting_Environment
from Gym.environments.division import Division_Environment
from Gym.environments.divisor_flip_expectation import DivisorFlipExpectation_Environment
from Gym.environments.double_cross_counting import DoubleCrossCounting_Environment
from Gym.environments.double_palindromic_string_counting import DoublePalindromicStringCounting_Environment
from Gym.environments.double_stack_sorting import DoubleStackSorting_Environment
from Gym.environments.dyn_dynamite import DynDynamite_Environment
from Gym.environments.eight_digit_puzzle import EightDigitPuzzle_Environment
from Gym.environments.emperor_worries import EmperorWorries_Environment
from Gym.environments.energy_storage_meter import EnergyStorageMeter_Environment
from Gym.environments.euclid_game import EuclidGame_Environment
from Gym.environments.even_degree_graph_partitioning import EvenDegreeGraphPartitioning_Environment
from Gym.environments.expression_adding_parenthese_counting import Expression_AddingParenthese_Counting_Environment
from Gym.environments.face_right_way import FaceRightWay_Environment
from Gym.environments.factorial_trailing_zero_count import FactorialTrailingZeroCount_Environment
from Gym.environments.fbi_binary_tree import FBI_BinaryTree_Environment
from Gym.environments.fibonacci import Fibonacci_Environment
from Gym.environments.fibonacci_containing_counting import FibonacciContainingCounting_Environment
from Gym.environments.fibtrain import Fibtrain_Environment
from Gym.environments.firework_show import FireworkShow_Environment
from Gym.environments.fixed_mod_k_selection_counting import FixedModK_Selection_Counting_Environment
from Gym.environments.fixed_one_edge_num_spanning_tree import FixedOneEdgeNum_SpanningTree_Environment
from Gym.environments.fractional_programming import FractionalProgramming_Environment
from Gym.environments.fractional_programming_bipartite_graph_matching import FractionalProgramming_BipartiteGraphMatching_Environment
from Gym.environments.futoshiki_puzzle import FutoshikiPuzzle_Environment
from Gym.environments.gas_fire_extinguishers import GasFireExtinguishers_Environment
from Gym.environments.gaussian_elimination import GaussianElimination_Environment
from Gym.environments.gcd_fibonacci_product import GCDFibonacciProduct_Environment
from Gym.environments.gcd_lcm_counting import GcdLcmCounting_Environment
from Gym.environments.gcd_one_counting import GCDOne_Counting_Environment
from Gym.environments.gcd_prime_counting import GCDPrime_Counting_Environment
from Gym.environments.gold_washing import GoldWashing_Environment
from Gym.environments.gra_minima_game import GraMinimaGame_Environment
from Gym.environments.grade_ranking_counting import GradeRankingCounting_Environment
from Gym.environments.graph_contain_tree_counting import GraphContainTreeCounting_Environment
from Gym.environments.graph_isomorphism import GraphIsomorphism_Environment
from Gym.environments.grid_bfs import GridBFS_Environment
from Gym.environments.grid_coloring_counting import GridColoringCounting_Environment
from Gym.environments.grid_component import GridComponent_Environment
from Gym.environments.grid_local_minimum_counting import GridLocalMinimumCounting_Environment
from Gym.environments.grid_path_counting_with_blocks import GridPathCountingWithBlocks_Environment
from Gym.environments.grid_parity_construction import GridParityConstruction_Environment
from Gym.environments.grid_triangle_counting import GridTriangleCounting_Environment
from Gym.environments.halving_chain_counting import HalvingChainCounting_Environment
from Gym.environments.hamiltonian_path import HamiltonianPath_Environment
from Gym.environments.hamiltonian_path_existence import HamiltonianPathExistence_Environment
from Gym.environments.heap_counting import HeapCounting_Environment
from Gym.environments.hitori_puzzle import HitoriPuzzle_Environment
from Gym.environments.hungry_rabbit import HungryRabbit_Environment
from Gym.environments.hur_warehouse_store import HURWarehouseStore_Environment
from Gym.environments.imp_party import ImpParty_Environment
from Gym.environments.individual_sum_bounded_sequence_counting import IndividualSumBounded_SequenceCounting_Environment
from Gym.environments.integer_factorization_counting import IntegerFactorizationCounting_Environment
from Gym.environments.integer_programming import IntegerProgramming_Environment
from Gym.environments.integral import Integral_Environment
from Gym.environments.inversion_pair import InversionPair_Environment
from Gym.environments.inversion_pair_k_counting import InversionPairK_Counting_Environment
from Gym.environments.josephus import Josephus_Environment
from Gym.environments.jug_puzzle import JugPuzzle_Environment
from Gym.environments.k_partition import KPartition_Environment
from Gym.environments.kakurasu import Kakurasu_Environment
from Gym.environments.kidding_me import KiddingMe_Environment
from Gym.environments.king_sorting import KingSorting_Environment
from Gym.environments.klo_blocks import KloBlocks_Environment
from Gym.environments.knapsack import Knapsack_Environment
from Gym.environments.knights_and_knaves import KnightsAndKnaves_Environment
from Gym.environments.kos_dicing import KosDicing_Environment
from Gym.environments.kth_binary_tree import Kth_BinaryTree_Environment
from Gym.environments.kth_semi_balanced_bracket_sequence import Kth_SemiBalancedBracketSequence_Environment
from Gym.environments.kth_subsequence import KthSubsequence_Environment
from Gym.environments.kur import KUR_Environment
from Gym.environments.lamp_changing import LampChanging_Environment
from Gym.environments.land_acquisition import LandAcquisition_Environment
from Gym.environments.landform_generation_counting import LandformGenerationCounting_Environment
from Gym.environments.largest_convex_polygon import LargestConvexPolygon_Environment
from Gym.environments.largest_rectangle_among_points import LargestRectangle_AmongPoints_Environment
from Gym.environments.las import LAS_Environment
from Gym.environments.las_laser import LASLaser_Environment
from Gym.environments.lcm import LCM_Environment
from Gym.environments.lds_two_counting import LDSTwo_Counting_Environment
from Gym.environments.light_up_puzzle import LightUpPuzzle_Environment
from Gym.environments.link_beads import LinkBeads_Environment
from Gym.environments.lis_lds_concatenation import LIS_LDS_Concatenation_Environment
from Gym.environments.liz_lollipop import LIZ_Lollipop_Environment
from Gym.environments.longest_double_palindrome import Longest_DoublePalindrome_Environment
from Gym.environments.longest_matching_subsequence import Longest_MatchingSubsequence_Environment
from Gym.environments.longest_maxdiff_bounded_interval import LongestMaxDiffBoundedInterval_Environment
from Gym.environments.longest_path import LongestPath_Environment
from Gym.environments.longest_repeated_palindrome import Longest_RepeatedPalindrome_Environment
from Gym.environments.maf_mafia import MafMafia_Environment
from Gym.environments.magic_square_puzzle import MagicSquarePuzzle_Environment
from Gym.environments.making_grade import MakingGrade_Environment
from Gym.environments.matrix_binary_exponentiation import Matrix_BinaryExponentiation_Environment
from Gym.environments.matrix_permutation_both_diagonal_one import MatrixPermutation_BothDiagonalOne_Environment
from Gym.environments.matrix_permutation_equivalence import MatrixPermutationEquivalence_Environment
from Gym.environments.matrix_permutation_main_diagonal_one import MatrixPermutation_MainDiagonalOne_Environment
from Gym.environments.matrix_pooling import MatrixPooling_Environment
from Gym.environments.matrix_rmq_counting import MatrixRMQCounting_Environment
from Gym.environments.max_different_group_pair_division import MaxDifferentGroupPairDivision_Environment
from Gym.environments.max_grid_path_intersection import MaxGridPathIntersection_Environment
from Gym.environments.max_minimum_after_interval_addition import MaxMinimum_AfterIntervalAddition_Environment
from Gym.environments.max_mult_split import MaxMultSplit_Environment
from Gym.environments.max_multiplication_fixed_sum import MaxMultiplicationFixedSum_Environment
from Gym.environments.max_no_conflicting_bombs import MaxNoConflictingBombs_Environment
from Gym.environments.max_nonadjacent_k_element_sum import Max_NonAdjacent_KElementSum_Environment
from Gym.environments.max_permutation import MaxPermutation_Environment
from Gym.environments.max_rmq_expectation import MaxRMQExpectation_Environment
from Gym.environments.max_segment_coverage_constraint import MaxSegmentCoverageConstraint_Environment
from Gym.environments.max_sum_lds import MaxSumLDS_Environment
from Gym.environments.max_three_square_sum import MaxThreeSquareSum_Environment
from Gym.environments.max_tree_constrained_permutation_weight import Max_TreeConstrainedPermutation_Weight_Environment
from Gym.environments.max_tree_k_path_coverage import MaxTree_KPathCoverahe_Environment
from Gym.environments.max_tree_xor_path import MaxTreeXorPath_Environment
from Gym.environments.max_weight_palindromic_substring import MaxWeightPalindromicSubstring_Environment
from Gym.environments.max_xor_path import MaxXorPath_Environment
from Gym.environments.max_xor_set import MaxXorSet_Environment
from Gym.environments.maximum_achromatic_number import MaximumAchromaticNumber_Environment
from Gym.environments.maximum_clique import MaximumClique_Environment
from Gym.environments.maximum_divisor import MaximumDivisor_Environment
from Gym.environments.maximum_independent_set_grid import MaximumIndependentSetGrid_Environment
from Gym.environments.maximum_independent_set_tree import Maximum_IndependentSet_Tree_Environment
from Gym.environments.maximum_lexicographical_order_subsequence import MaximumLexicographicalOrderSubsequence_Environment
from Gym.environments.maximum_point_segment_matching import MaximumPointSegmentMatching_Environment
from Gym.environments.maximum_subsequence_num import Maximum_SubsequenceNum_Environment
from Gym.environments.maximum_weight_matching import MaximumWeightMatching_Environment
from Gym.environments.maze import Maze_Environment
from Gym.environments.min_conversion_to_cycle_cost import MinConversionToCycleCost_Environment
from Gym.environments.min_cost_reducing_lnds import MinCostReducingLNDS_Environment
from Gym.environments.min_cost_tree_coverage import MinCostTreeCoverage_Environment
from Gym.environments.min_cube_assignment import MinCubeAssignment_Environment
from Gym.environments.min_division_sum_xor import MinDivisionSumXor_Environment
from Gym.environments.min_inorder_binary_tree import MinInorderBinaryTree_Environment
from Gym.environments.min_kdivisor_number import MinKDivisorNumber_Environment
from Gym.environments.min_no_solution_linear_diophantine_equation import MinNoSolutionLinearDiophantineEquation_Environment
from Gym.environments.min_nonsubstring import MinNonsubstring_Environment
from Gym.environments.min_pairsum_multiplication_permutation import MinPairSumMultiplicationPermutation_Environment
from Gym.environments.min_path_cover_dag import MinPathCover_DAG_Environment
from Gym.environments.min_sum_chebyshev_distance import MinSumChebyshevDistance_Environment
from Gym.environments.min_sum_distance_square import MinSumDistanceSquare_Environment
from Gym.environments.min_sum_pre_xor import MinSumPreXor_Environment
from Gym.environments.min_swap_two_permutations import MinSwapTwoPermutations_Environment
from Gym.environments.min_xor_pair import MinXorPair_Environment
from Gym.environments.minesweeping import Minesweeping_Environment
from Gym.environments.minimal_cyclic_shift import MinimalCyclicShift_Environment
from Gym.environments.minimum_chromatic_number import MinimumChromaticNumber_Environment
from Gym.environments.minimum_chromatic_number_segment_overlap import MinimumChromaticNumber_SegmentOverlap_Environment
from Gym.environments.minimum_cost_maximum_flow import MinimumCost_MaximumFlow_Environment
from Gym.environments.minimum_crossing_edges_graph_partition import Minimum_CrossingEdges_GraphPartition_Environment
from Gym.environments.minimum_directed_spanning_tree import MinimumDirectedSpanningTree_Environment
from Gym.environments.minimum_dominating_interval import Minimum_DominatingInterval_Environment
from Gym.environments.minimum_dominating_set import Minimum_DominatingSet_Environment
from Gym.environments.minimum_dominating_set_grid import Minimum_DominatingSet_Grid_Environment
from Gym.environments.minimum_fibonacci_representation import MinimumFibonacciRepresentation_Environment
from Gym.environments.minimum_harmonious_chromatic_number import MinimumHarmoniousChromaticNumber_Environment
from Gym.environments.minimum_interval_coverage import MinimumIntervalCoverage_Environment
from Gym.environments.minimum_max_abs_slicer import Minimum_MaxAbsSlicer_Environment
from Gym.environments.minimum_max_slicer import Minimum_MaxSlicer_Environment
from Gym.environments.minimum_ratio_path import MinimumRatioPath_Environment
from Gym.environments.minimum_spanning_tree import MinimumSpanningTree_Environment
from Gym.environments.minimum_spanning_tree_counting import MinimumSpanningTreeCounting_Environment
from Gym.environments.minimum_steiner_tree import MinimumSteinerTree_Environment
from Gym.environments.minimum_sum_difference_submatrix import MinimumSumDifferenceSubmatrix_Environment
from Gym.environments.minimum_tree_weighted_dominating_ancestor import MinimumTreeWeightedDominatingAncestor_Environment
from Gym.environments.minimum_unconflicted_grid_kmax import MinimumUnconflictedGridKMax_Environment
from Gym.environments.minimum_vertex_cover import Minimum_VertexCover_Environment
from Gym.environments.minimum_weighted_spanning_tree import MinimumWeightedSpanningTree_Environment
from Gym.environments.mitter_transportation import MitterTransportation_Environment
from Gym.environments.mixed_graph_eulerian_circuit import MixedGraphEulerianCircuit_Environment
from Gym.environments.money_charging_game import MoneyChargingGame_Environment
from Gym.environments.monochrome_block_counting import MonochromeBlockCounting_Environment
from Gym.environments.monotonic_stack import MonotonicStack_Environment
from Gym.environments.most_component_tree_removing_two_paths import MostComponentTreeRemovingTwoPaths_Environment
from Gym.environments.most_num_edge_non_self_isomorphism import MostNumEdge_NonSelfIsomorphism_Environment
from Gym.environments.multidrink import MultiDrink_Environment
from Gym.environments.multiple_flipping_game import MultipleFlippingGame_Environment
from Gym.environments.multiplication import Multiplication_Environment
from Gym.environments.myj import MYJ_Environment
from Gym.environments.nand_result_counting import NANDResultCounting_Environment
from Gym.environments.negative_base import NegativeBase_Environment
from Gym.environments.new_nim_game import NewNimGame_Environment
from Gym.environments.next_palindromic import NextPalindromic_Environment
from Gym.environments.nine_puzzle import NinePuzzle_Environment
from Gym.environments.no_adjacent_girl_counting import NoAdjacentGirlCounting_Environment
from Gym.environments.no_double_triple_counting import NoDoubleTripleCounting_Environment
from Gym.environments.not_containing_string_counting import NotContainingStringCounting_Environment
from Gym.environments.number_partition_counting import NumberPartitionCounting_Environment
from Gym.environments.numbrix import Numbrix_Environment
from Gym.environments.odd_visitation import OddVisitation_Environment
from Gym.environments.odl_distance import ODLDistance_Environment
from Gym.environments.pair_more_one_counting import PairMoreOneCounting_Environment
from Gym.environments.palembang_bridges import PalembangBridges_Environment
from Gym.environments.palindrome_partition_counting import PalindromePartitionCounting_Environment
from Gym.environments.palindromic_substring_number_counting import PalindromicSubstringNumberCounting_Environment
from Gym.environments.pan_solar_panels import PanSolarPanels_Environment
from Gym.environments.path_no_going_back_counting import Path_NoGoingBack_Counting_Environment
from Gym.environments.patrol import Patrol_Environment
from Gym.environments.pcp_permutation import PCPPermutation_Environment
from Gym.environments.pipeline_arrangement import PipelineArrangement_Environment
from Gym.environments.pol_polarization import POLPolarization_Environment
from Gym.environments.polya_model import PolyaModel_Environment
from Gym.environments.polynomial_factorization import PolynomialFactorization_Environment
from Gym.environments.polynomial_interpolation import PolynomialInterpolation_Environment
from Gym.environments.polynomial_minimum import PolynomialMinimum_Environment
from Gym.environments.polynomial_remainder import PolynomialRemainder_Environment
from Gym.environments.power_cycle import PowerCycle_Environment
from Gym.environments.power_shortcut import PowerShortcut_Environment
from Gym.environments.powernest import PowerNest_Environment
from Gym.environments.prefix_concatenation import PrefixConcatenation_Environment
from Gym.environments.prefix_product_mod_distinct_permutation import PrefixProductMODDistinctPermutation_Environment
from Gym.environments.prefix_sum_mod_distinct_permutation import PrefixSumMODDistinctPermutation_Environment
from Gym.environments.prefixuffix import Prefixuffix_Environment
from Gym.environments.preorder_traversal import PreorderTraversal_Environment
from Gym.environments.prime_graph_minimum_chromatic_number import PrimeGraph_MinimumChromaticNumber_Environment
from Gym.environments.protecting_flowers import ProtectingFlowers_Environment
from Gym.environments.pythagorean_graph_independent_set_counting import PythagoreanGraph_IndependentSetCounting_Environment
from Gym.environments.quad_magic_items import QuadMagicItems_Environment
from Gym.environments.quadratic_function_segmentation import QuadraticFunctionSegmentation_Environment
from Gym.environments.quantum_lock_puzzle import QuantumLockPuzzle_Environment
from Gym.environments.queen_placement import QueenPlacement_Environment
from Gym.environments.random_range_max_expectation import RandomRangeMaxExpectation_Environment
from Gym.environments.range_constrained_increasing_sequence_counting import RangeConstrained_IncreasingSequence_Counting_Environment
from Gym.environments.range_four_sequence_construction import RangeFourSequenceConstruction_Environment
from Gym.environments.range_shrinking_sequence_counting import RangeShrinkingSequenceCounting_Environment
from Gym.environments.recursive_function import RecursiveFunction_Environment
from Gym.environments.recursive_sequence_sum_construction import RecursiveSequenceSumConstruction_Environment
from Gym.environments.repeat_sequence_lnds import RepeatSequenceLNDS_Environment
from Gym.environments.root_extraction import RootExtraction_Environment
from Gym.environments.round_robin import RoundRobin_Environment
from Gym.environments.roundtable_assignment import RoundTableAssignment_Environment
from Gym.environments.royal_lock_counting import RoyalLockCounting_Environment
from Gym.environments.salad_bar import SaladBar_Environment
from Gym.environments.salesman_fatigue import SalesmanFatigue_Environment
from Gym.environments.same_adjacency_counting import SameAdjacencyCounting_Environment
from Gym.environments.sat import SAT_Environment
from Gym.environments.scc_sequence_counting import SCC_Sequence_Counting_Environment
from Gym.environments.secret_cow_code import SecretCowCode_Environment
from Gym.environments.segment_min_length_equal_counting import SegmentMinLengthEqual_Counting_Environment
from Gym.environments.segment_tree_sorting_counting import SegmentTreeSortingCounting_Environment
from Gym.environments.self_power_sequence_mod import SelfPowerSequenceMOD_Environment
from Gym.environments.set_cover import SetCover_Environment
from Gym.environments.set_splitting import SetSplitting_Environment
from Gym.environments.shared_substring_counting import SharedSubstringCounting_Environment
from Gym.environments.shortest_path import ShortestPath_Environment
from Gym.environments.shortest_path_count_construction import ShortestPathCountConstruction_Environment
from Gym.environments.shortest_unicolor_substring import ShortestUnicolorSubstring_Environment
from Gym.environments.singing_girl_story import SingingGirlStory_Environment
from Gym.environments.single_stack_sorting import SingleStackSorting_Environment
from Gym.environments.ska_rock_garden import SkaRockGarden_Environment
from Gym.environments.skyscraper_puzzle import SkyscraperPuzzle_Environment
from Gym.environments.skyscraper_sum_puzzle import SkyscraperSumPuzzle_Environment
from Gym.environments.sliding_window import SlidingWindow_Environment
from Gym.environments.slo_elephants import SLOElephants_Environment
from Gym.environments.smallest_binary_multiple import SmallestBinaryMultiple_Environment
from Gym.environments.smallest_circle import SmallestCircle_Environment
from Gym.environments.sorting import Sorting_Environment
from Gym.environments.spiral_matrix import SpiralMatrix_Environment
from Gym.environments.splitting_game import SplittingGame_Environment
from Gym.environments.spy_network import SpyNetwork_Environment
from Gym.environments.squ_squarks import SquSquarks_Environment
from Gym.environments.square_undamaged_point_counting import SquareUndamagedPointCounting_Environment
from Gym.environments.star_battle import StarBattle_Environment
from Gym.environments.stirling_second import StirlingSecond_Environment
from Gym.environments.stone_game import StoneGame_Environment
from Gym.environments.stone_intervals_game import StoneIntervalsGame_Environment
from Gym.environments.string_partition_shuffle import StringPartitionShuffle_Environment
from Gym.environments.string_reversal_construction import StringReversalConstruction_Environment
from Gym.environments.stu_well import STUWell_Environment
from Gym.environments.stunt_flying import StuntFlying_Environment
from Gym.environments.subarray_sum_xor import SubarraySumXor_Environment
from Gym.environments.subarray_xor_sum import SubarrayXorSum_Environment
from Gym.environments.subgraph_isomorphism import SubgraphIsomorphism_Environment
from Gym.environments.submatrix_sum_divisible_counting import SubmatrixSumDivisibleCounting_Environment
from Gym.environments.subsequence_reversal_lnds import SubsequenceReversalLNDS_Environment
from Gym.environments.subset_sum import SubsetSum_Environment
from Gym.environments.subset_sum_sequence import SubsetSumSequence_Environment
from Gym.environments.sudoku import Sudoku_Environment
from Gym.environments.sum_divisor_num import Sum_DivisorNum_Environment
from Gym.environments.sum_gcd import SumGCD_Environment
from Gym.environments.sum_gcd_with_individual import SumGCDWithIndividual_Environment
from Gym.environments.sum_lcm import SumLCM_Environment
from Gym.environments.sum_manhattan_curved_surface import SumManhattan_CurvedSurface_Environment
from Gym.environments.sum_mod import SumMOD_Environment
from Gym.environments.sum_phi_interval import SumPHIInterval_Environment
from Gym.environments.sum_product_divisor_num import SumProductDivisorNum_Environment
from Gym.environments.sum_pseudo_euclidean import SumPseudoEuclidean_Environment
from Gym.environments.sum_set_multiplication import SumSetMultiplication_Environment
from Gym.environments.sum_spanning_tree_gcd import SumSpanningTreeGCD_Environment
from Gym.environments.sum_triangle_area import SumTriangleArea_Environment
from Gym.environments.sum_xor_divisor_num import SumXorDivisorNum_Environment
from Gym.environments.survo_puzzle import SurvoPuzzle_Environment
from Gym.environments.taking_prime_game import TakingPrimeGame_Environment
from Gym.environments.task_arrangement import TaskArrangement_Environment
from Gym.environments.tetris_attack import TetrisAttack_Environment
from Gym.environments.three_string_common_subsequence_counting import ThreeStringCommonSubsequenceCounting_Environment
from Gym.environments.three_vertex_cycle_counting import ThreeVertexCycleCounting_Environment
from Gym.environments.topological_sort import TopologicalSort_Environment
from Gym.environments.topological_sort_minimal_lexicographical_order import TopologicalSort_MinimalLexicographicalOrder_Environment
from Gym.environments.tournament_longest_path import Tournament_LongestPath_Environment
from Gym.environments.transmission_delay import TransmissionDelay_Environment
from Gym.environments.tree_add_one_edge_diameter import TreeAddOneEdgeDiameter_Environment
from Gym.environments.tree_center import TreeCenter_Environment
from Gym.environments.tree_change_one_edge_diameter import TreeChangeOneEdgeDiameter_Environment
from Gym.environments.tree_coloring import TreeColoring_Environment
from Gym.environments.tree_distance_equal_triad_counting import Tree_DistanceEqualTriad_Counting_Environment
from Gym.environments.tree_dynamic_xor_zero_path import TreeDynamic_XORZeroPath_Environment
from Gym.environments.tree_elimination_expectation import TreeElimination_Expectation_Environment
from Gym.environments.tree_even_partitioning import TreeEvenPartitioning_Environment
from Gym.environments.tree_maximum_visited_vertex import TreeMaximumVisitedVertex_Environment
from Gym.environments.tree_random_walk_expectation import TreeRandomWalkExpectation_Environment
from Gym.environments.tree_topological_sequence_counting import TreeTopologicalSequenceCounting_Environment
from Gym.environments.triumphal_arch import TriumphalArch_Environment
from Gym.environments.twiddle_puzzle import TwiddlePuzzle_Environment
from Gym.environments.two_sat import TwoSAT_Environment
from Gym.environments.two_set_all_coprime_counting import TwoSet_AllCoprime_Counting_Environment
from Gym.environments.undamaged_submatrix_counting import UndamagedSubmatrixCounting_Environment
from Gym.environments.value_diminishing_selection import ValueDiminishingSelection_Environment
from Gym.environments.vertex_k_center import Vertex_KCenter_Environment
from Gym.environments.virus_synthesis import VirusSynthesis_Environment
from Gym.environments.visible_line import VisibleLine_Environment
from Gym.environments.warehouse_construction import WarehouseConstruction_Environment
from Gym.environments.weighted_binarytree import WeightedBinaryTree_Environment
from Gym.environments.weighted_lis import WeightedLIS_Environment
from Gym.environments.whack_a_mole import WhackAMole_Environment
from Gym.environments.wil import WIL_Environment
from Gym.environments.wyc import WYC_Environment
from Gym.environments.wyr_leveling_ground import WYRLevelingGround_Environment
from Gym.environments.xor_equation_counting import XorEquationCounting_Environment
from Gym.environments.zero_prefix_subset_counting import ZeroPrefixSubsetCounting_Environment


identifier2environment = {
    "ABProgramSimulation" : ABProgramSimulation_Environment,
    "AddMultiple_Divisible_Counting" : AddMultiple_Divisible_Counting_Environment,
    "AdditionTable" : AdditionTable_Environment,
    "AlmostCompleteGraphCycleCounting" : AlmostCompleteGraphCycleCounting_Environment,
    "AndOr_Sequence_Counting" : AndOr_Sequence_Counting_Environment,
    "AntiPalindromicSubstringCounting" : AntiPalindromicSubstringCounting_Environment,
    "Axis_KCenter" : Axis_KCenter_Environment,
    "BAJBytecomputer" : BAJBytecomputer_Environment,
    "BannedPointSupersetPathCounting" : BannedPointSupersetPathCounting_Environment,
    "BanyanHeart" : BanyanHeart_Environment,
    "BEZMinimalistSecurity" : BEZMinimalistSecurity_Environment,
    "BezoutIdentity" : BezoutIdentity_Environment,
    "Binario" : Binario_Environment,
    "Binario_NoAdjacencyRequirement" : Binario_NoAdjacencyRequirement_Environment,
    "BinaryAlternation" : BinaryAlternation_Environment,
    "BinaryStringNoAdjacentCount" : BinaryStringNoAdjacentCount_Environment,
    "binary_string_no_adjacent_count" : BinaryStringNoAdjacentCount_Environment,
    "BinaryLinearEquation_SolutionCounting" : BinaryLinearEquation_SolutionCounting_Environment,
    "BinaryTreeLeafNumExpectation" : BinaryTreeLeafNumExpectation_Environment,
    "BitEquationCounting" : BitEquationCounting_Environment,
    "BitAndZero_PathCounting" : BitAndZero_PathCounting_Environment,
    "BitwiseOperationSequenceCounting" : BitwiseOperationSequenceCounting_Environment,
    "BlockImage" : BlockImage_Environment,
    "BoundedAdjacencyDifference_Permutation_Counting" : BoundedAdjacencyDifference_Permutation_Counting_Environment,
    "BoundedIntervalIntersection" : BoundedIntervalIntersection_Environment,
    "BoundedMeanSubarrayCounting" : BoundedMeanSubarrayCounting_Environment,
    "BoundedSubarrayCounting" : BoundedSubarrayCounting_Environment,
    "BoxScheduling" : BoxScheduling_Environment,
    "Bridge" : Bridge_Environment,
    "BubbleSwapLowerBound_PermutationCounting" : BubbleSwapLowerBound_PermutationCounting_Environment,
    "BucketSorting" : BucketSorting_Environment,
    "CampfireParty" : CampfireParty_Environment,
    "CampsitePuzzle" : CampsitePuzzle_Environment,
    "Canon" : Canon_Environment,
    "CantorExpansion" : CantorExpansion_Environment,
    "CapitalCityEffect" : CapitalCityEffect_Environment,
    "CardColoringCounting" : CardColoringCounting_Environment,
    "CatalanNumberMod" : CatalanNumberMod_Environment,
    "CheckAllCycleXorZero" : CheckAllCycleXorZero_Environment,
    "ChoHamsters" : ChoHamsters_Environment,
    "Cinema" : Cinema_Environment,
    "Circuit" : Circuit_Environment,
    "CirculatingDecimalCounting" : CirculatingDecimalCounting_Environment,
    "CirculatingGrid" : CirculatingGrid_Environment,
    "CleaningUp" : CleaningUp_Environment,
    "ClearSymmetry" : ClearSymmetry_Environment,
    "Clique_IndependentSet_Partitioning_Counting" : Clique_IndependentSet_Partitioning_Counting_Environment,
    "CoinSquareGame" : CoinSquareGame_Environment,
    "ColoringCounting" : ColoringCounting_Environment,
    "CombinationOddSubsequenceCounting" : CombinationOddSubsequenceCounting_Environment,
    "ConcatenationPartitionCountingSum" : ConcatenationPartitionCountingSum_Environment,
    "CongruentEquation" : CongruentEquation_Environment,
    "ConstructHackInterval" : ConstructHackInterval_Environment,
    "ConvexHull" : ConvexHull_Environment,
    "Cornfield" : Cornfield_Environment,
    "CountdownEqual" : CountdownEqual_Environment, "CountdownClose" : CountdownClose_Environment,
    "CowDanceShow" : CowDanceShow_Environment,
    "CRT" : CRT_Environment,
    "Cryptarithmetic" : Cryptarithmetic_Environment,
    "Cube_FixedLocalMaximumCounting" : Cube_FixedLocalMaximumCounting_Environment,
    "CycleCounting" : CycleCounting_Environment,
    "DecreasingDigitCounting" : DecreasingDigitCounting_Environment,
    "DegreeFixed_SpanningTree" : DegreeFixed_SpanningTree_Environment,
    "DeltaMinPopcount" : DeltaMinPopcount_Environment,
    "DeltaNimGame" : DeltaNimGame_Environment,
    "DerangementExtension" : DerangementExtension_Environment,
    "DifferenceConstraintSystem" : DifferenceConstraintSystem_Environment,
    "DifferenceConstraintSystemDAG" : DifferenceConstraintSystemDAG_Environment,
    "DifferentColorPairing" : DifferentColorPairing_Environment,
    "Differentiate" : Differentiate_Environment,
    "DigitLISCounting" : DigitLISCounting_Environment,
    "DigitSumInterval" : DigitSumInterval_Environment,
    "digit_sum_interval" : DigitSumInterval_Environment,
    "DiscreteLogarithm" : DiscreteLogarithm_Environment,
    "Disinfection" : Disinfection_Environment,
    "DistinctArrayPermutation" : DistinctArrayPermutation_Environment,
    "DistinctEdgeColoredCompleteGraphCounting" : DistinctEdgeColoredCompleteGraphCounting_Environment,
    "Division" : Division_Environment,
    "DivisorFlipExpectation" : DivisorFlipExpectation_Environment,
    "DoubleCrossCounting" : DoubleCrossCounting_Environment,
    "DoublePalindromicStringCounting" : DoublePalindromicStringCounting_Environment,
    "DoubleStackSorting" : DoubleStackSorting_Environment,
    "DynDynamite" : DynDynamite_Environment,
    "EightDigitPuzzle" : EightDigitPuzzle_Environment,
    "EmperorWorries" : EmperorWorries_Environment,
    "EnergyStorageMeter" : EnergyStorageMeter_Environment,
    "EuclidGame" : EuclidGame_Environment,
    "EvenDegreeGraphPartitioning" : EvenDegreeGraphPartitioning_Environment,
    "Expression_AddingParenthese_Counting" : Expression_AddingParenthese_Counting_Environment,
    "FaceRightWay" : FaceRightWay_Environment,
    "FactorialTrailingZeroCount" : FactorialTrailingZeroCount_Environment,
    "FBI_BinaryTree" : FBI_BinaryTree_Environment,
    "Fibonacci" : Fibonacci_Environment,
    "FibonacciContainingCounting" : FibonacciContainingCounting_Environment,
    "Fibtrain" : Fibtrain_Environment,
    "FireworkShow" : FireworkShow_Environment,
    "FixedModK_Selection_Counting" : FixedModK_Selection_Counting_Environment,
    "FixedOneEdgeNum_SpanningTree" : FixedOneEdgeNum_SpanningTree_Environment,
    "FractionalProgramming" : FractionalProgramming_Environment,
    "FractionalProgramming_BipartiteGraphMatching" : FractionalProgramming_BipartiteGraphMatching_Environment,
    "FutoshikiPuzzle" : FutoshikiPuzzle_Environment,
    "GasFireExtinguishers" : GasFireExtinguishers_Environment,
    "GaussianElimination" : GaussianElimination_Environment,
    "GCDFibonacciProduct" : GCDFibonacciProduct_Environment,
    "GcdLcmCounting" : GcdLcmCounting_Environment,
    "GCDOne_Counting" : GCDOne_Counting_Environment,
    "GCDPrime_Counting" : GCDPrime_Counting_Environment,
    "GoldWashing" : GoldWashing_Environment,
    "GraMinimaGame" : GraMinimaGame_Environment,
    "GradeRankingCounting" : GradeRankingCounting_Environment,
    "GraphContainTreeCounting" : GraphContainTreeCounting_Environment,
    "GraphIsomorphism" : GraphIsomorphism_Environment,
    "GridBFS" : GridBFS_Environment,
    "GridColoringCounting" : GridColoringCounting_Environment,
    "GridComponent" : GridComponent_Environment,
    "GridLocalMinimumCounting" : GridLocalMinimumCounting_Environment,
    "GridPathCountingWithBlocks" : GridPathCountingWithBlocks_Environment,
    "grid_path_counting_with_blocks" : GridPathCountingWithBlocks_Environment,
    "GridParityConstruction" : GridParityConstruction_Environment,
    "GridTriangleCounting" : GridTriangleCounting_Environment,
    "HalvingChainCounting" : HalvingChainCounting_Environment,
    "HamiltonianPath" : HamiltonianPath_Environment,
    "HamiltonianPathExistence" : HamiltonianPathExistence_Environment,
    "HeapCounting" : HeapCounting_Environment,
    "HitoriPuzzle" : HitoriPuzzle_Environment,
    "HungryRabbit" : HungryRabbit_Environment,
    "HURWarehouseStore" : HURWarehouseStore_Environment,
    "ImpParty" : ImpParty_Environment,
    "IndividualSumBounded_SequenceCounting" : IndividualSumBounded_SequenceCounting_Environment,
    "IntegerFactorizationCounting" : IntegerFactorizationCounting_Environment,
    "IntegerProgramming" : IntegerProgramming_Environment,
    "Integral" : Integral_Environment,
    "InversionPair" : InversionPair_Environment,
    "InversionPairK_Counting" : InversionPairK_Counting_Environment,
    "Josephus" : Josephus_Environment,
    "JugPuzzle" : JugPuzzle_Environment,
    "KPartition" : KPartition_Environment,
    "Kakurasu" : Kakurasu_Environment,
    "KiddingMe" : KiddingMe_Environment,
    "KingSorting" : KingSorting_Environment,
    "KloBlocks" : KloBlocks_Environment,
    "Knapsack" : Knapsack_Environment,
    "KnightsAndKnaves" : KnightsAndKnaves_Environment,
    "KosDicing" : KosDicing_Environment,
    "Kth_BinaryTree" : Kth_BinaryTree_Environment,
    "Kth_SemiBalancedBracketSequence" : Kth_SemiBalancedBracketSequence_Environment,
    "KthSubsequence" : KthSubsequence_Environment,
    "KUR" : KUR_Environment,
    "LampChanging" : LampChanging_Environment,
    "LandAcquisition" : LandAcquisition_Environment,
    "LandformGenerationCounting" : LandformGenerationCounting_Environment,
    "LargestConvexPolygon" : LargestConvexPolygon_Environment,
    "LargestRectangle_AmongPoints" : LargestRectangle_AmongPoints_Environment,
    "LAS" : LAS_Environment,
    "LASLaser" : LASLaser_Environment,
    "LCM" : LCM_Environment,
    "LDSTwo_Counting" : LDSTwo_Counting_Environment,
    "LightUpPuzzle" : LightUpPuzzle_Environment,
    "LinkBeads" : LinkBeads_Environment,
    "LIS_LDS_Concatenation" : LIS_LDS_Concatenation_Environment,
    "LIZ_Lollipop" : LIZ_Lollipop_Environment,
    "Longest_DoublePalindrome" : Longest_DoublePalindrome_Environment,
    "Longest_MatchingSubsequence" : Longest_MatchingSubsequence_Environment,
    "LongestMaxDiffBoundedInterval" : LongestMaxDiffBoundedInterval_Environment,
    "LongestPath" : LongestPath_Environment,
    "Longest_RepeatedPalindrome" : Longest_RepeatedPalindrome_Environment,
    "MafMafia" : MafMafia_Environment,
    "MagicSquarePuzzle" : MagicSquarePuzzle_Environment,
    "MakingGrade" : MakingGrade_Environment,
    "Matrix_BinaryExponentiation" : Matrix_BinaryExponentiation_Environment,
    "MatrixPermutation_BothDiagonalOne" : MatrixPermutation_BothDiagonalOne_Environment,
    "MatrixPermutationEquivalence" : MatrixPermutationEquivalence_Environment,
    "MatrixPermutation_MainDiagonalOne" : MatrixPermutation_MainDiagonalOne_Environment,
    "MatrixPooling" : MatrixPooling_Environment,
    "MatrixRMQCounting" : MatrixRMQCounting_Environment,
    "MaxDifferentGroupPairDivision" : MaxDifferentGroupPairDivision_Environment,
    "MaxGridPathIntersection" : MaxGridPathIntersection_Environment,
    "MaxMinimum_AfterIntervalAddition" : MaxMinimum_AfterIntervalAddition_Environment,
    "MaxMultSplit" : MaxMultSplit_Environment,
    "MaxMultiplicationFixedSum" : MaxMultiplicationFixedSum_Environment,
    "MaxNoConflictingBombs" : MaxNoConflictingBombs_Environment,
    "Max_NonAdjacent_KElementSum" : Max_NonAdjacent_KElementSum_Environment,
    "MaxPermutation" : MaxPermutation_Environment,
    "MaxRMQExpectation" : MaxRMQExpectation_Environment,
    "MaxSegmentCoverageConstraint" : MaxSegmentCoverageConstraint_Environment,
    "MaxSumLDS" : MaxSumLDS_Environment,
    "MaxThreeSquareSum" : MaxThreeSquareSum_Environment,
    "Max_TreeConstrainedPermutation_Weight" : Max_TreeConstrainedPermutation_Weight_Environment,
    "MaxTree_KPathCoverage" : MaxTree_KPathCoverahe_Environment,
    "MaxTreeXorPath" : MaxTreeXorPath_Environment,
    "MaxWeightPalindromicSubstring" : MaxWeightPalindromicSubstring_Environment,
    "MaxXorPath" : MaxXorPath_Environment,
    "MaxXorSet" : MaxXorSet_Environment,
    "MaximumAchromaticNumber" : MaximumAchromaticNumber_Environment,
    "MaximumClique" : MaximumClique_Environment,
    "MaximumDivisor" : MaximumDivisor_Environment,
    "MaximumIndependentSetGrid" : MaximumIndependentSetGrid_Environment,
    "Maximum_IndependentSet_Tree" : Maximum_IndependentSet_Tree_Environment,
    "MaximumLexicographicalOrderSubsequence" : MaximumLexicographicalOrderSubsequence_Environment,
    "MaximumPointSegmentMatching" : MaximumPointSegmentMatching_Environment,
    "Maximum_SubsequenceNum" : Maximum_SubsequenceNum_Environment,
    "MaximumWeightMatching" : MaximumWeightMatching_Environment,
    "Maze" : Maze_Environment,
    "MinConversionToCycleCost" : MinConversionToCycleCost_Environment,
    "MinCostReducingLNDS" : MinCostReducingLNDS_Environment,
    "MinCostTreeCoverage" : MinCostTreeCoverage_Environment,
    "MinCubeAssignment" : MinCubeAssignment_Environment,
    "MinDivisionSumXor" : MinDivisionSumXor_Environment,
    "MinInorderBinaryTree" : MinInorderBinaryTree_Environment,
    "MinKDivisorNumber" : MinKDivisorNumber_Environment,
    "MinNoSolutionLinearDiophantineEquation" : MinNoSolutionLinearDiophantineEquation_Environment,
    "MinNonsubstring" : MinNonsubstring_Environment,
    "MinPairSumMultiplicationPermutation" : MinPairSumMultiplicationPermutation_Environment,
    "MinPathCover_DAG" : MinPathCover_DAG_Environment,
    "MinSumChebyshevDistance" : MinSumChebyshevDistance_Environment,
    "MinSumDistanceSquare" : MinSumDistanceSquare_Environment,
    "MinSumPreXor" : MinSumPreXor_Environment,
    "MinSwapTwoPermutations" : MinSwapTwoPermutations_Environment,
    "MinXorPair" : MinXorPair_Environment,
    "Minesweeping" : Minesweeping_Environment,
    "MinimalCyclicShift" : MinimalCyclicShift_Environment,
    "MinimumChromaticNumber" : MinimumChromaticNumber_Environment,
    "MinimumChromaticNumber_SegmentOverlap" : MinimumChromaticNumber_SegmentOverlap_Environment,
    "MinimumCost_MaximumFlow" : MinimumCost_MaximumFlow_Environment,
    "Minimum_CrossingEdges_GraphPartition" : Minimum_CrossingEdges_GraphPartition_Environment,
    "MinimumDirectedSpanningTree" : MinimumDirectedSpanningTree_Environment,
    "Minimum_DominatingInterval" : Minimum_DominatingInterval_Environment,
    "Minimum_DominatingSet" : Minimum_DominatingSet_Environment,
    "Minimum_DominatingSet_Grid" : Minimum_DominatingSet_Grid_Environment,
    "MinimumFibonacciRepresentation" : MinimumFibonacciRepresentation_Environment,
    "MinimumHarmoniousChromaticNumber" : MinimumHarmoniousChromaticNumber_Environment,
    "MinimumIntervalCoverage" : MinimumIntervalCoverage_Environment,
    "Minimum_MaxAbsSlicer" : Minimum_MaxAbsSlicer_Environment,
    "Minimum_MaxSlicer" : Minimum_MaxSlicer_Environment,
    "MinimumRatioPath" : MinimumRatioPath_Environment,
    "MinimumSpanningTree" : MinimumSpanningTree_Environment,
    "MinimumSpanningTreeCounting" : MinimumSpanningTreeCounting_Environment,
    "MinimumSteinerTree" : MinimumSteinerTree_Environment,
    "MinimumSumDifferenceSubmatrix" : MinimumSumDifferenceSubmatrix_Environment,
    "MinimumTreeWeightedDominatingAncestor" : MinimumTreeWeightedDominatingAncestor_Environment,
    "MinimumUnconflictedGridKMax" : MinimumUnconflictedGridKMax_Environment,
    "Minimum_VertexCover" : Minimum_VertexCover_Environment,
    "MinimumWeightedSpanningTree" : MinimumWeightedSpanningTree_Environment,
    "MitterTransportation" : MitterTransportation_Environment,
    "MixedGraphEulerianCircuit" : MixedGraphEulerianCircuit_Environment,
    "MoneyChargingGame" : MoneyChargingGame_Environment,
    "MonochromeBlockCounting" : MonochromeBlockCounting_Environment,
    "MonotonicStack" : MonotonicStack_Environment,
    "MostComponentTreeRemovingTwoPaths" : MostComponentTreeRemovingTwoPaths_Environment,
    "MostNumEdge_NonSelfIsomorphism" : MostNumEdge_NonSelfIsomorphism_Environment,
    "MultiDrink" : MultiDrink_Environment,
    "MultipleFlippingGame" : MultipleFlippingGame_Environment,
    "Multiplication" : Multiplication_Environment,
    "MYJ" : MYJ_Environment,
    "NANDResultCounting" : NANDResultCounting_Environment,
    "NegativeBase" : NegativeBase_Environment,
    "NewNimGame" : NewNimGame_Environment,
    "NextPalindromic" : NextPalindromic_Environment,
    "NinePuzzle" : NinePuzzle_Environment,
    "NoAdjacentGirlCounting" : NoAdjacentGirlCounting_Environment,
    "NoDoubleTripleCounting" : NoDoubleTripleCounting_Environment,
    "NotContainingStringCounting" : NotContainingStringCounting_Environment,
    "NumberPartitionCounting" : NumberPartitionCounting_Environment,
    "Numbrix" : Numbrix_Environment,
    "OddVisitation" : OddVisitation_Environment,
    "ODLDistance" : ODLDistance_Environment,
    "PairMoreOneCounting" : PairMoreOneCounting_Environment,
    "PalembangBridges" : PalembangBridges_Environment,
    "PalindromePartitionCounting" : PalindromePartitionCounting_Environment,
    "PalindromicSubstringNumberCounting" : PalindromicSubstringNumberCounting_Environment,
    "PanSolarPanels" : PanSolarPanels_Environment,
    "Path_NoGoingBack_Counting" : Path_NoGoingBack_Counting_Environment,
    "Patrol" : Patrol_Environment,
    "PCPPermutation" : PCPPermutation_Environment,
    "PipelineArrangement" : PipelineArrangement_Environment,
    "POLPolarization" : POLPolarization_Environment,
    "PolyaModel" : PolyaModel_Environment,
    "PolynomialFactorization" : PolynomialFactorization_Environment,
    "PolynomialInterpolation" : PolynomialInterpolation_Environment,
    "PolynomialMinimum" : PolynomialMinimum_Environment,
    "PolynomialRemainder" : PolynomialRemainder_Environment,
    "PowerCycle" : PowerCycle_Environment,
    "PowerShortcut" : PowerShortcut_Environment,
    "PowerNest" : PowerNest_Environment,
    "PrefixConcatenation" : PrefixConcatenation_Environment,
    "PrefixProductMODDistinctPermutation" : PrefixProductMODDistinctPermutation_Environment,
    "PrefixSumMODDistinctPermutation" : PrefixSumMODDistinctPermutation_Environment,
    "Prefixuffix" : Prefixuffix_Environment,
    "PreorderTraversal" : PreorderTraversal_Environment,
    "PrimeGraph_MinimumChromaticNumber" : PrimeGraph_MinimumChromaticNumber_Environment,
    "ProtectingFlowers" : ProtectingFlowers_Environment,
    "PythagoreanGraph_IndependentSetCounting" : PythagoreanGraph_IndependentSetCounting_Environment,
    "QuadMagicItems" : QuadMagicItems_Environment,
    "QuadraticFunctionSegmentation" : QuadraticFunctionSegmentation_Environment,
    "QuantumLockPuzzle" : QuantumLockPuzzle_Environment,
    "QueenPlacement" : QueenPlacement_Environment,
    "RandomRangeMaxExpectation" : RandomRangeMaxExpectation_Environment,
    "RangeConstrained_IncreasingSequence_Counting" : RangeConstrained_IncreasingSequence_Counting_Environment,
    "RangeFourSequenceConstruction" : RangeFourSequenceConstruction_Environment,
    "RangeShrinkingSequenceCounting" : RangeShrinkingSequenceCounting_Environment,
    "RecursiveFunction" : RecursiveFunction_Environment,
    "RecursiveSequenceSumConstruction" : RecursiveSequenceSumConstruction_Environment,
    "RepeatSequenceLNDS" : RepeatSequenceLNDS_Environment,
    "RootExtraction" : RootExtraction_Environment,
    "RoundRobin" : RoundRobin_Environment,
    "RoundTableAssignment" : RoundTableAssignment_Environment,
    "RoyalLockCounting" : RoyalLockCounting_Environment,
    "SaladBar" : SaladBar_Environment,
    "SalesmanFatigue" : SalesmanFatigue_Environment,
    "SameAdjacencyCounting" : SameAdjacencyCounting_Environment,
    "SAT" : SAT_Environment,
    "SCC_Sequence_Counting" : SCC_Sequence_Counting_Environment,
    "SecretCowCode" : SecretCowCode_Environment,
    "SegmentMinLengthEqual_Counting" : SegmentMinLengthEqual_Counting_Environment,
    "SegmentTreeSortingCounting" : SegmentTreeSortingCounting_Environment,
    "SelfPowerSequenceMOD" : SelfPowerSequenceMOD_Environment,
    "SetCover" : SetCover_Environment,
    "SetSplitting" : SetSplitting_Environment,
    "SharedSubstringCounting" : SharedSubstringCounting_Environment,
    "ShortestPath" : ShortestPath_Environment,
    "ShortestPathCountConstruction" : ShortestPathCountConstruction_Environment,
    "ShortestUnicolorSubstring" : ShortestUnicolorSubstring_Environment,
    "SingingGirlStory" : SingingGirlStory_Environment,
    "SingleStackSorting" : SingleStackSorting_Environment,
    "SkaRockGarden" : SkaRockGarden_Environment,
    "SkyscraperPuzzle" : SkyscraperPuzzle_Environment,
    "SkyscraperSumPuzzle" : SkyscraperSumPuzzle_Environment,
    "SlidingWindow" : SlidingWindow_Environment,
    "SLOElephants" : SLOElephants_Environment,
    "SmallestBinaryMultiple" : SmallestBinaryMultiple_Environment,
    "SmallestCircle" : SmallestCircle_Environment,
    "Sorting" : Sorting_Environment,
    "SpiralMatrix" : SpiralMatrix_Environment,
    "SplittingGame" : SplittingGame_Environment,
    "SpyNetwork" : SpyNetwork_Environment,
    "SquSquarks" : SquSquarks_Environment,
    "SquareUndamagedPointCounting" : SquareUndamagedPointCounting_Environment,
    "StarBattle" : StarBattle_Environment,
    "StirlingSecond" : StirlingSecond_Environment,
    "StoneGame" : StoneGame_Environment,
    "StoneIntervalsGame" : StoneIntervalsGame_Environment,
    "StringPartitionShuffle" : StringPartitionShuffle_Environment,
    "StringReversalConstruction" : StringReversalConstruction_Environment,
    "STUWell" : STUWell_Environment,
    "StuntFlying" : StuntFlying_Environment,
    "SubarraySumXor" : SubarraySumXor_Environment,
    "SubarrayXorSum" : SubarrayXorSum_Environment,
    "SubgraphIsomorphism" : SubgraphIsomorphism_Environment,
    "SubmatrixSumDivisibleCounting" : SubmatrixSumDivisibleCounting_Environment,
    "SubsequenceReversalLNDS" : SubsequenceReversalLNDS_Environment,
    "SubsetSum" : SubsetSum_Environment,
    "SubsetSumSequence" : SubsetSumSequence_Environment,
    "Sudoku" : Sudoku_Environment,
    "Sum_DivisorNum" : Sum_DivisorNum_Environment,
    "SumGCD" : SumGCD_Environment,
    "SumGCDWithIndividual" : SumGCDWithIndividual_Environment,
    "SumLCM" : SumLCM_Environment,
    "SumManhattan_CurvedSurface" : SumManhattan_CurvedSurface_Environment,
    "SumMOD" : SumMOD_Environment,
    "SumPHIInterval" : SumPHIInterval_Environment,
    "SumProductDivisorNum" : SumProductDivisorNum_Environment,
    "SumPseudoEuclidean" : SumPseudoEuclidean_Environment,
    "SumSetMultiplication" : SumSetMultiplication_Environment,
    "SumSpanningTreeGCD" : SumSpanningTreeGCD_Environment,
    "SumTriangleArea" : SumTriangleArea_Environment,
    "SumXorDivisorNum" : SumXorDivisorNum_Environment,
    "SurvoPuzzle" : SurvoPuzzle_Environment,
    "TakingPrimeGame" : TakingPrimeGame_Environment,
    "TaskArrangement" : TaskArrangement_Environment,
    "TetrisAttack" : TetrisAttack_Environment,
    "ThreeStringCommonSubsequenceCounting" : ThreeStringCommonSubsequenceCounting_Environment,
    "ThreeVertexCycleCounting" : ThreeVertexCycleCounting_Environment,
    "TopologicalSort" : TopologicalSort_Environment,
    "TopologicalSort_MinimalLexicographicalOrder" : TopologicalSort_MinimalLexicographicalOrder_Environment,
    "Tournament_LongestPath" : Tournament_LongestPath_Environment,
    "TransmissionDelay" : TransmissionDelay_Environment,
    "TreeAddOneEdgeDiameter" : TreeAddOneEdgeDiameter_Environment,
    "TreeCenter" : TreeCenter_Environment,
    "TreeChangeOneEdgeDiameter" : TreeChangeOneEdgeDiameter_Environment,
    "TreeColoring" : TreeColoring_Environment,
    "Tree_DistanceEqualTriad_Counting" : Tree_DistanceEqualTriad_Counting_Environment,
    "TreeDynamic_XORZeroPath" : TreeDynamic_XORZeroPath_Environment,
    "TreeElimination_Expectation" : TreeElimination_Expectation_Environment,
    "TreeEvenPartitioning" : TreeEvenPartitioning_Environment,
    "TreeMaximumVisitedVertex" : TreeMaximumVisitedVertex_Environment,
    "TreeRandomWalkExpectation" : TreeRandomWalkExpectation_Environment,
    "TreeTopologicalSequenceCounting" : TreeTopologicalSequenceCounting_Environment,
    "TriumphalArch" : TriumphalArch_Environment,
    "TwiddlePuzzle" : TwiddlePuzzle_Environment,
    "TwoSAT" : TwoSAT_Environment,
    "TwoSet_AllCoprime_Counting" : TwoSet_AllCoprime_Counting_Environment,
    "UndamagedSubmatrixCounting" : UndamagedSubmatrixCounting_Environment,
    "ValueDiminishingSelection" : ValueDiminishingSelection_Environment,
    "Vertex_KCenter" : Vertex_KCenter_Environment,
    "VirusSynthesis" : VirusSynthesis_Environment,
    "VisibleLine" : VisibleLine_Environment,
    "WarehouseConstruction" : WarehouseConstruction_Environment,
    "WeightedBinaryTree" : WeightedBinaryTree_Environment,
    "WeightedLIS" : WeightedLIS_Environment,
    "WhackAMole" : WhackAMole_Environment,
    "WIL" : WIL_Environment,
    "WYC" : WYC_Environment,
    "WYRLevelingGround" : WYRLevelingGround_Environment,
    "XorEquationCounting" : XorEquationCounting_Environment,
    "ZeroPrefixSubsetCounting" : ZeroPrefixSubsetCounting_Environment,
}